### ISSUE TITLE
Failed to load 'resnet50_netdef'

### ISSUE THREAD

**Issue by rarvind33** [triton-inference-server/server#1935]
**Description**
I am running Triton via a kubernetes deployment, where the pod is set to use 3 GPUs. On running the deployment I get the below error -

```
kubectl logs triton-3gpu-575b64c578-65gw2 -n triton

2020-08-27 08:14:49.149376: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
I0827 08:14:49.184434 1 metrics.cc:164] found 3 GPUs supporting NVML metrics
I0827 08:14:49.190249 1 metrics.cc:173]   GPU 0: Tesla T4
I0827 08:14:49.196444 1 metrics.cc:173]   GPU 1: Tesla T4
I0827 08:14:49.202433 1 metrics.cc:173]   GPU 2: Tesla T4
I0827 08:14:49.202691 1 server.cc:127] Initializing Triton Inference Server
I0827 08:14:49.669202 1 server_status.cc:55] New status tracking for model 'densenet_onnx'
I0827 08:14:49.669235 1 server_status.cc:55] New status tracking for model 'inception_graphdef'
I0827 08:14:49.669247 1 server_status.cc:55] New status tracking for model 'resnet50_netdef'
I0827 08:14:49.669257 1 server_status.cc:55] New status tracking for model 'simple'
I0827 08:14:49.669267 1 server_status.cc:55] New status tracking for model 'simple_string'
I0827 08:14:49.669504 1 model_repository_manager.cc:723] loading: inception_graphdef:1
I0827 08:14:49.669807 1 model_repository_manager.cc:723] loading: densenet_onnx:1
I0827 08:14:49.670122 1 model_repository_manager.cc:723] loading: resnet50_netdef:1
I0827 08:14:49.670398 1 model_repository_manager.cc:723] loading: simple:1
I0827 08:14:49.670747 1 model_repository_manager.cc:723] loading: simple_string:1
I0827 08:14:49.679886 1 base_backend.cc:176] Creating instance inception_graphdef_0_gpu0 on GPU 0 (7.5) using model.graphdef
I0827 08:14:49.680274 1 base_backend.cc:176] Creating instance simple_0_gpu0 on GPU 0 (7.5) using model.graphdef
I0827 08:14:49.680495 1 base_backend.cc:176] Creating instance simple_string_0_gpu0 on GPU 0 (7.5) using model.graphdef
2020-08-27 08:14:49.726444: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2600000000 Hz
2020-08-27 08:14:49.732021: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f51ec171580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-27 08:14:49.732055: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-27 08:14:49.732228: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-08-27 08:14:49.733496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:49.734347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:49.735154: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:49.735170: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:49.735194: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:49.735224: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:49.735234: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:49.772649: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:49.772735: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:49.772772: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:49.785027: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
I0827 08:14:49.792859 1 onnx_backend.cc:203] Creating instance densenet_onnx_0_gpu0 on GPU 0 (7.5) using model.onnx
I0827 08:14:50.133113 1 netdef_backend.cc:206] Creating instance resnet50_netdef_0_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
I0827 08:14:53.303072 1 onnx_backend.cc:203] Creating instance densenet_onnx_0_gpu1 on GPU 1 (7.5) using model.onnx
I0827 08:14:55.378121 1 onnx_backend.cc:203] Creating instance densenet_onnx_0_gpu2 on GPU 2 (7.5) using model.onnx
2020-08-27 08:14:55.974485: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:55.974524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:55.974529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:55.974532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:55.974550: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:55.978503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:55.980422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:55.982404: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
2020-08-27 08:14:55.987114: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f4fd3fe2080 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-27 08:14:55.987130: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-08-27 08:14:55.987133: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
2020-08-27 08:14:55.987136: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): Tesla T4, Compute Capability 7.5
2020-08-27 08:14:55.991091: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:55.993211: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:55.995374: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:55.995422: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:55.995439: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:55.995456: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:55.995471: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:55.995506: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:55.995557: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:55.995572: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.007141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.007261: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.007273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.007282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.007289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.007295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.012387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.013924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.014969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
2020-08-27 08:14:56.018908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.021042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.023446: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.023500: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.023516: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.023532: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.023548: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.023586: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.023604: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.023618: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.034094: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.034184: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.034203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.034225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.034240: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.034256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.039582: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.040705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.041709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.074908 1 base_backend.cc:176] Creating instance simple_string_0_gpu1 on GPU 1 (7.5) using model.graphdef
2020-08-27 08:14:56.077897: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.080042: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.082447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.082498: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.082517: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.082534: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.082551: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.082582: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.082614: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.082635: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.092257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.092324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.092335: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.092343: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.092351: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.092358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.097431: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.098496: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.099599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.101236 1 base_backend.cc:176] Creating instance simple_0_gpu1 on GPU 1 (7.5) using model.graphdef
2020-08-27 08:14:56.104447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.106895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.109325: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.109389: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.109415: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.109440: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.109516: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.109559: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.109581: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.109604: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.122079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.122169: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.122183: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.122192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.122200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.122209: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.127978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.129057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.170426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.172713 1 base_backend.cc:176] Creating instance simple_string_0_gpu2 on GPU 2 (7.5) using model.graphdef
2020-08-27 08:14:56.175895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.178271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.180382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.180430: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.180447: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.180464: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.180479: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.180511: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.180531: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.180546: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.191559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.191628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.191639: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.191647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.191654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.191661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.197614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.198669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.199698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.201861 1 base_backend.cc:176] Creating instance simple_0_gpu2 on GPU 2 (7.5) using model.graphdef
I0827 08:14:56.202797 1 model_repository_manager.cc:888] successfully loaded 'simple_string' version 1
2020-08-27 08:14:56.205223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.207673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.210155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.210211: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.210234: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.210256: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.210277: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.210316: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.210340: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.210362: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.222617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.222664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.222673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.222680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.222686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.222692: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.227857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.272517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.274772: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.278479 1 model_repository_manager.cc:888] successfully loaded 'simple' version 1
I0827 08:14:56.470743 1 base_backend.cc:176] Creating instance inception_graphdef_0_gpu1 on GPU 1 (7.5) using model.graphdef
2020-08-27 08:14:56.473686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.475313: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.476928: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.476965: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.476977: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.476989: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.476999: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.477021: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.477030: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.477040: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.484954: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.485009: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.485018: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.485024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.485030: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.485035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.489893: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.490790: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.491674: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.700067 1 base_backend.cc:176] Creating instance inception_graphdef_0_gpu2 on GPU 2 (7.5) using model.graphdef
2020-08-27 08:14:56.705559: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:18:00.0
2020-08-27 08:14:56.708062: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 1 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:af:00.0
2020-08-27 08:14:56.708903: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1634] Found device 2 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:d8:00.0
2020-08-27 08:14:56.708924: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.11.0
2020-08-27 08:14:56.708929: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.11
2020-08-27 08:14:56.708934: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-08-27 08:14:56.708938: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-08-27 08:14:56.708952: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-08-27 08:14:56.708957: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.11
2020-08-27 08:14:56.708963: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.8
2020-08-27 08:14:56.713607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1762] Adding visible gpu devices: 0, 1, 2
2020-08-27 08:14:56.713642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1175] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 08:14:56.713648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181]      0 1 2
2020-08-27 08:14:56.713652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 0:   N Y Y
2020-08-27 08:14:56.713655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 1:   Y N Y
2020-08-27 08:14:56.713658: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1194] 2:   Y Y N
2020-08-27 08:14:56.716738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13219 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:18:00.0, compute capability: 7.5)
2020-08-27 08:14:56.717646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13219 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
2020-08-27 08:14:56.718580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1320] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 13526 MB memory) -> physical GPU (device: 2, name: Tesla T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0827 08:14:56.986750 1 model_repository_manager.cc:888] successfully loaded 'inception_graphdef' version 1
I0827 08:14:57.496563 1 model_repository_manager.cc:888] successfully loaded 'densenet_onnx' version 1
[E context_gpu.cu:452] Encountered following in ~CUDAContext: [enforce fail at context_gpu.h:203] . Encountered CUDA error: invalid argument
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7f529c69bab7 in /opt/tritonserver/bin/../lib/pytorch/libc10.so)
frame #1: <unknown function> + 0xd23932 (0x7f529d5e2932 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #2: caffe2::CUDAContext::~CUDAContext() + 0x4b (0x7f529f937b5b in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #3: <unknown function> + 0x33461ee (0x7f529fc051ee in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #4: <unknown function> + 0x336e6c4 (0x7f529fc2d6c4 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #5: <unknown function> + 0x336e82e (0x7f529fc2d82e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #6: std::_Function_handler<std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (caffe2::OperatorDef const&, caffe2::Workspace*), std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (*)(caffe2::OperatorDef const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, caffe2::OperatorDef const&, caffe2::Workspace*&&) + 0x23 (0x7f531a79cdb3 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #7: <unknown function> + 0x1cac1bc (0x7f531a6961bc in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #8: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0x499 (0x7f531a697699 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #9: caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x193 (0x7f531a688833 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #10: <unknown function> + 0x1ca134e (0x7f531a68b34e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #11: std::_Function_handler<std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*), std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (*)(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*&&) + 0x23 (0x7f531a662c23 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #12: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x4a5 (0x7f531a654d25 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #13: caffe2::CreateNet(caffe2::NetDef const&, caffe2::Workspace*) + 0x9e (0x7f531a65581e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #14: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x34 (0x7f531a6d8414 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #15: <unknown function> + 0x1ca648e (0x7f531a69048e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #16: Caffe2WorkspaceCreate + 0xc4d (0x7f531a69227d in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #17: <unknown function> + 0x25887d (0x7f537d7cc87d in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #18: <unknown function> + 0x25a992 (0x7f537d7ce992 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #19: <unknown function> + 0x2518b3 (0x7f537d7c58b3 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #20: <unknown function> + 0x11ce7a (0x7f537d690e7a in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #21: <unknown function> + 0x11e2f5 (0x7f537d6922f5 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #22: <unknown function> + 0xbd6df (0x7f537cc686df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #23: <unknown function> + 0x76db (0x7f537d35c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #24: clone + 0x3f (0x7f537c32588f in /lib/x86_64-linux-gnu/libc.so.6)

E0827 08:14:58.059269 1 model_repository_manager.cc:891] failed to load 'resnet50_netdef' version 1: Internal: load failed for 'resnet50_netdef': [enforce fail at context_gpu.cu:323] error == cudaSuccess. 1 vs 0. Error at: /tmp/pip-req-build-xy84e8f7/caffe2/core/context_gpu.cu:323: invalid argument
frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x67 (0x7f529c69bab7 in /opt/tritonserver/bin/../lib/pytorch/libc10.so)
frame #1: <unknown function> + 0x307b7ef (0x7f529f93a7ef in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #2: <unknown function> + 0x1c364a6 (0x7f531a6204a6 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #3: caffe2::empty(c10::ArrayRef<long>, c10::TensorOptions) + 0x32a (0x7f531a6c6aea in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #4: caffe2::ReinitializeTensor(caffe2::Tensor*, c10::ArrayRef<long>, c10::TensorOptions) + 0x1e4 (0x7f531a6c6e74 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #5: <unknown function> + 0x336d5fd (0x7f529fc2c5fd in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #6: <unknown function> + 0x336e4d8 (0x7f529fc2d4d8 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #7: <unknown function> + 0x336e82e (0x7f529fc2d82e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cuda.so)
frame #8: std::_Function_handler<std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (caffe2::OperatorDef const&, caffe2::Workspace*), std::unique_ptr<caffe2::OperatorBase, std::default_delete<caffe2::OperatorBase> > (*)(caffe2::OperatorDef const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, caffe2::OperatorDef const&, caffe2::Workspace*&&) + 0x23 (0x7f531a79cdb3 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #9: <unknown function> + 0x1cac1bc (0x7f531a6961bc in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #10: caffe2::CreateOperator(caffe2::OperatorDef const&, caffe2::Workspace*, int) + 0x499 (0x7f531a697699 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #11: caffe2::SimpleNet::SimpleNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x193 (0x7f531a688833 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #12: <unknown function> + 0x1ca134e (0x7f531a68b34e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #13: std::_Function_handler<std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*), std::unique_ptr<caffe2::NetBase, std::default_delete<caffe2::NetBase> > (*)(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*)>::_M_invoke(std::_Any_data const&, std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*&&) + 0x23 (0x7f531a662c23 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #14: caffe2::CreateNet(std::shared_ptr<caffe2::NetDef const> const&, caffe2::Workspace*) + 0x4a5 (0x7f531a654d25 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #15: caffe2::CreateNet(caffe2::NetDef const&, caffe2::Workspace*) + 0x9e (0x7f531a65581e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #16: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x34 (0x7f531a6d8414 in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #17: <unknown function> + 0x1ca648e (0x7f531a69048e in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #18: Caffe2WorkspaceCreate + 0xc4d (0x7f531a69227d in /opt/tritonserver/bin/../lib/pytorch/libtorch_cpu.so)
frame #19: <unknown function> + 0x25887d (0x7f537d7cc87d in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #20: <unknown function> + 0x25a992 (0x7f537d7ce992 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #21: <unknown function> + 0x2518b3 (0x7f537d7c58b3 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #22: <unknown function> + 0x11ce7a (0x7f537d690e7a in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #23: <unknown function> + 0x11e2f5 (0x7f537d6922f5 in /opt/tritonserver/bin/../lib/libtritonserver.so)
frame #24: <unknown function> + 0xbd6df (0x7f537cc686df in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #25: <unknown function> + 0x76db (0x7f537d35c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #26: clone + 0x3f (0x7f537c32588f in /lib/x86_64-linux-gnu/libc.so.6)

I0827 08:14:58.062385 1 model_repository_manager.cc:865] successfully unloaded 'simple_string' version 1
I0827 08:14:58.064418 1 model_repository_manager.cc:865] successfully unloaded 'simple' version 1
I0827 08:14:58.091895 1 model_repository_manager.cc:865] successfully unloaded 'inception_graphdef' version 1
I0827 08:14:58.109842 1 model_repository_manager.cc:865] successfully unloaded 'densenet_onnx' version 1
error: creating server: Internal - failed to load all models
```

When I try to spin up a deployment using a single GPU, I do not have any issues.

**Triton Information**

2.1.0 – NGC Container v20.07

Are you using the Triton container or did you build it yourself?

I am pulling this image - nvcr.io/nvidia/tritonserver:20.07-v1-py3

**To Reproduce**
Two K8 worker nodes with 3 NVIDIA T4 GPUs each.
2 Deployments -
    1. 1 Pod w/ 1 Replica using 3 GPUs
    2. 3 Pods via replica count of 3, each pod using 1 GPU

Server - NetApp HCI H615c

Operating System - Ubuntu 18.04.4 LTS

GPU Driver - 440.64.00

CUDA Version - 10.2

GPU Device Plugin - 0.6.0

DeepOps - 20.08

Kubernetes - 1.17.9

**Comment by deadeyegoodwin** [comment]
It appears to be a problem in the Caffe2 framework. Have you tried running with just the netdef model and not the others. A couple of things to note:

1. the 20.07 release notes indicate that the release requires CUDA 11 and driver 450 or later. https://docs.nvidia.com/deeplearning/triton-inference-server/release-notes/rel_20-07.html#rel_20-07

2. Caffe2 is deprecated and will be removed very soon.

**Comment by rarvind33** [comment]
I built the model repository following these steps -
```
git checkout r20.07
cd docs/examples
./fetch_models.sh
```

Please note that I do not have any issues when I setup Triton as a K8s Pod with a single GPU.
I am facing this issue when I spin up a Triton K8s Pod with 3 x NVIDIA T4 GPUs.

As per the link you have shared, I do see that the required version of CUDA is included in the container and the T4 GPUs can work with driver v440.30.

My NVIDIA Tesla Driver version is 440.64.00, which was installed by GPU Operator and it looks like that is the latest version that I can get to with GPU Operator.

**Comment by deadeyegoodwin** [comment]
Did you try running with a repository that contains only the netdef model?
So you have CUDA 11 installed on the host? Above you mention CUDA 10.2.

**Comment by khoa-ho** [comment]
@deadeyegoodwin I think his host CUDA is still 10.2 but he assumed the CUDA 11 installed in the container should be enough.

@rarvind33 Is this something you experienced only for resnet50? Did you try using only GPU1 (not 0 and 2) in the 3GPU case? (relaying a question from another on the team)

**Comment by deadeyegoodwin** [comment]
The CUDA library (libcuda) is actually mapped into the container from the host system. The cuda runtime (which is a software layer on top of libcuda that most applications use) is inside the container. But CUDA 11 should be installed on the host system. Or run an older version of Triton that is based on CUDA 10.2.

**Comment by deadeyegoodwin** [comment]
@rarvind33 Please let us know about the questions in comment https://github.com/triton-inference-server/server/issues/1935#issuecomment-682109585 and reopen.

**Comment by rarvind33** [comment]
@deadeyegoodwin the issue was resolved when I loaded only the netdef model in the model repo.
As per @khoa-ho 's inputs, I am using v20.03.1.

I will try the same approach with v20.07 and let you know.
