### ISSUE TITLE
Cannot deploy on AWS EKS gpu nodes (p3, g4, etc.)

### ISSUE THREAD

**Issue by thecooltechguy** [triton-inference-server/server#2107]
**Description**
We are trying to deploy this in a production cluster to replace tf serving (which we're facing low gpu utilization issues with), but we're facing the following problem that is preventing us from launching nvidia triton inference server on eks.

Specifically, when we deploy the nvidia triton inference server on EKS (k8s 1.17) with gpu nodes, we get the following startup error:

```code
I1012 05:29:58.777135 1 metrics.cc:184] found 1 GPUs supporting NVML metrics
I1012 05:29:58.782558 1 metrics.cc:193]   GPU 0: Tesla T4
I1012 05:29:58.782745 1 server.cc:120] Initializing Triton Inference Server
I1012 05:29:58.782756 1 server.cc:121]   id: 'triton'
I1012 05:29:58.782760 1 server.cc:122]   version: '2.3.0'
I1012 05:29:58.782766 1 server.cc:128]   extensions:  classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics
E1012 05:29:58.782909 1 pinned_memory_manager.cc:192] failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version
```

Note the last line's error.

Next, it attempts to load all models, but for each model, it fails with the same message. Here is an example output for one of the models:

```code
E1012 05:30:04.365919 1 model_repository_manager.cc:899] failed to load 'test_model' version 1: Internal: unable to auto-complete model configuration for 'test_model', failed to load model: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version
2020-10-12 05:30:04.366514: I tensorflow/cc/saved_model/loader.cc:332] SavedModel load for tags { serve }; Status: fail. Took 188297 microseconds.
```

As shown here (https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html#eks-gpu-ami-versions), the Nvidia driver version in the AWS EKS optimized accelerated AMIs is `418.87.00`. 

And https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html says that:

```
if you are running on Tesla (for example, T4 or any other Tesla board), you may use NVIDIA driver release 418.xx or 440.30.
```

So, we thought that launching a g4dn.xlarge (which has T4 gpus) instance with the latest EKS 1.17 optimized accelerated AMI `ami-08655818c336c3a28` (with Nvidia driver version 418.87.00) should work without an issue.

So is triton server deployable with EKS 1.17?

**Triton Information**
Triton k8s deployment image version: nvcr.io/nvidia/tritonserver:20.09-py3

Are you using the Triton container or did you build it yourself?
Triton container on EKS as a k8s deployment

**To Reproduce**
Launch an EKS cluster with any gpu node with the AMI ID `ami-08655818c336c3a28` (I tried g4dn.xlarge and p3.2xlarge instances) and try to schedule a triton inference server on that node and you will get my error.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

I used tensorflow 2 models hosted on s3 (which the container is able to access and download and even attempt to load, after which it fails with the above mentioned error) and I set --strict-model-config=false (since the models are in TF SavedModel format) and I pass in the s3 repo path as: --model-store=s3://...

**Expected behavior**
Triton inference server should startup and run successfully

**Comment by thecooltechguy** [comment]
I was able to resolve this issue by just building a custom GPU based AMI with https://github.com/awslabs/amazon-eks-ami that installed the latest NVIDIA drivers (Version 450+), and now my triton inference server GPU pods on EKS are able to startup and run successfully.
