### ISSUE TITLE
Wrong results when using an onnx model with tensorrt gpu_execution_accelerator and dynamic axes

### ISSUE THREAD

**Issue by nimral** [triton-inference-server/server#2135]
I am using Triton to run inference of an Electra model exported by `torch.onnx.export()` from HuggingFace transformers. Without 
`gpu_execution_accelerator` in the config file OR without any dynamic axes (e.g. -1 in a shape or `max_batch_size`), it runs fine. But with the following config
```
name: "electra_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 512 
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [ 512 ]
  },  
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [ 512 ]
  },  
  {
    name: "token_type_ids"
    data_type: TYPE_INT64
    dims: [ 512 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1 ] 
  }
]
optimization { execution_accelerators {
  gpu_execution_accelerator : [ { name : "tensorrt" } ] 
}}
```
 the results are wrong (except for the first one in the batch).

  **Triton Information**
  Docker image: NVIDIA Release 20.09 (build 16016295)

**Comment by deadeyegoodwin** [comment]
Thanks for the report, we will look into it.

**Comment by flyingmrwang** [comment]
the same problem on r20.10, the first one in batch is correct and stable, others are zeros in most cases.
And sometimes become abnormal numbers like "30554476512240266213496184594321375232.000000"

**Comment by philipp-schmidt** [comment]
@flyingmrwang I saw similar problems and reverted to 19.10. I wrote more regarding the matter in #2231

**Comment by flyingmrwang** [comment]
@philipp-schmidt Thanks for you information. It seems like I should have a try of 20.11.

**Comment by deadeyegoodwin** [comment]
@philipp-schmidt  Are you still seeing this failure with the latest triton? If so I will move this issue to the onnxruntime-backend repo so that it gets the attention of the appropriate developers.

**Comment by philipp-schmidt** [comment]
Hello @deadeyegoodwin 
Thanks for returning to this issue.

Whenever I was using at least two clients I got wrong results looking like memory violations (results of one client appearing in the result of a different client, but also competely malformed responses). The issue did not exist in 19.10, which is what we are using in production right now.

I didn't have time to reproduce the behavior with a minimal example yet unfortunately.

Could the race condition you recently fixed be the source of the above issue that I'm seeing? If so I will check the latest version of triton ASAP.

**Comment by philipp-schmidt** [comment]
@deadeyegoodwin Is https://github.com/triton-inference-server/server/commit/98a46fe03075cc4962a73856e1e440ad22fba821 the fix of the racecondition?

**Comment by deadeyegoodwin** [comment]
The second... https://github.com/triton-inference-server/server/commit/4593850a76f94ef03b650f2dbe437d52c6dee4d1

The race condition only impacts the tensorrt backend so shouldn't impact onnx models. You are right that we haven't had a release since those fixes (next release is 21.02 at end of Feb.), so you will need to build it yourself to try it now. Master branch also has latest ONNX Runtime release, version 1.6.

**Comment by philipp-schmidt** [comment]
I am actually using the TensorRT backend (with this [model](https://github.com/isarsoft/yolov4-triton-tensorrt)). The problem was so hard to track down, I checked every issue which was similar. This one seemed similar.

I will check master branch, thanks again.

**Comment by philipp-schmidt** [comment]
Issue resolved for me. Problem was identical to https://github.com/triton-inference-server/server/issues/2339.
Master branch has the issue fixed.

**Comment by deadeyegoodwin** [comment]
Great! Closing.
