### ISSUE TITLE
[Libtorch] Triton server produces inconsistent results when hosting multiple models in one GPU

### ISSUE THREAD

**Issue by zmy1116** [triton-inference-server/server#2339]
**Description**
With the triton server hosting multiple model on one GPU, we see inconsistent result when GPU is heavily used (same inputs, different and incorrect outputs). 

We created a minimal example in the following repository to reproduce this issue:
 https://github.com/zmy1116/tritoninferenceissues 
In this example, we create two TensorRT models from TorchVision's `resnet18` and `inceptionv3` using NVIDIA torch2trt. We launch 4 inference jobs for each of the two models with the same inputs. There is significant discrepancy in the results using the same model on the same input.

So far in our test, this error seems only happen when multiple models are running within the same GPU heavily. This issues seems to not model dependent. We have seen the issues on our production models with various backbone:
- resnet
- inceptionnet
- efficientnet
- lstm

**Triton Information**
What version of Triton are you using?
We use triton 2.5.0
Are you using the Triton container or did you build it yourself?
We directly use the NGC container nvcr.io/nvidia/tritonserver:20.11-py3

**Aditional system information**

The problem occure on AWS VM instance type `g4dn.2xlarge` It contains one T4 GPU.
The models in model repository are all TensoRT model, created in the correspondent NGC container nvcr.io/nvidia/tensorrt:20.11-py3

**To Reproduce**

We created a minimal example in the following repository to reproduce this issue:
 https://github.com/zmy1116/tritoninferenceissues 

To summarize the steps:

- donwload and decompress the data folder `trt_issues_data` from the google drive link https://drive.google.com/file/d/1hBOpXMxSbeYbPltR23oJuzfdCxg6t1eo/view?usp=sharing

  The data folder consists of:
    - model repository for triton server `model_repository_2011`, two tensorrt models `resnet18` and `inceptionv3` are included
    - example inputs `testing_inputs.p`

- download the repository https://github.com/zmy1116/tritoninferenceissues

- start the triton server 
```buildoutcfg
# assume the model repository is at /home/ubuntu/trt_issues_data/model_repository_2011
docker run -d --gpus=all --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v /home/ubuntu/trt_issues_data/model_repository_2011:/models -e CUDA_VISIBLE_DEVICES=0 nvcr.io/nvidia/tritonserver:20.11-py3 tritonserver --model-repository=/models --strict-model-config=false
```

- use python grpc client to invoke 2 models multiple times and store multiple runs results. For one T4 machine, I run:
    - each model 4 jobs
    - each job runs 64 times of inputs with size 64x3x224x224
 
```buildoutcfg
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs1.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs5.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs2.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs6.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs3.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs7.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs4.p &
nohup python /home/ubuntu/tritoninferenceissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs8.p &

```
I think the important thing here is to run GPU intensively enough (so that GPU reaches at least 80%+ utils).

In the above specific setup, outputs 1-4 are from model `resnet18`, output 5-8 are from model `inceptionv3`, since i passed the same inputs they should return the same outputs. However, when comparing the results you should see signifcant discrepancies:
```buildoutcfg
f1 = pickle.load(open('/home/ubuntu/outputs1.p','rb'))
f2 = pickle.load(open('/home/ubuntu/outputs2.p','rb'))
f3 = pickle.load(open('/home/ubuntu/outputs3.p','rb'))
f4 = pickle.load(open('/home/ubuntu/outputs4.p','rb'))

f5 = pickle.load(open('/home/ubuntu/outputs5.p','rb'))
f6 = pickle.load(open('/home/ubuntu/outputs6.p','rb'))
f7 = pickle.load(open('/home/ubuntu/outputs7.p','rb'))
f8 = pickle.load(open('/home/ubuntu/outputs8.p','rb'))
for entry in [f2,f3,f4]:
    print(np.max(np.abs(f1-entry)))
for entry in [f7,f6,f8]:
    print(np.max(np.abs(f5-entry)))
```
![error](https://user-images.githubusercontent.com/45111899/102056007-b3d11400-3db9-11eb-8888-e03ded498cf6.PNG)

You can certainly generate the inputs data TensorRT models yourself, the inputs data is just a random generated array of size 64x3x224x224, the two models are from torchvision directly

```buildoutcfg

import torch
import torchvision

model = torchvision.models.resnet18(pretrained=True).cuda().half().eval()
data = torch.randn((1, 3, 224, 224)).cuda().half()
with open('/workspace/ubuntu/model_repository_2011/resnet18/1/model', "wb") as f:
    f.write(model_trt.engine.serialize())

model = torchvision.models.inception_v3(pretrained=True).cuda().half().eval()
data = torch.randn((1, 3, 224, 224)).cuda().half()
with open('/workspace/ubuntu/model_repository_2011/inceptionv3/1/model', "wb") as f:
    f.write(model_trt.engine.serialize())

```

**Expected behavior**

I think we should expect for the same model (of course, that is supposed to give deterministics result) should return correct and consistent result for the same inputs.  

What we see in our actual work is that the discrepancies are significantly large. The more models we host, the larger magnitude the errors are. Without using TritonServer, we can confirm that these models produce consistent results when running only one model on GPU.  

Let me know if you need additional information.

**Comment by CoderHam** [comment]
I am unable to reproduce the discrepancy in results from tritonserver with multiple models on a single GPU.
An few things to note:
1. Despite using FP16 (half) while preparing your models you are passing FP64 in testing_inputs.p 
2. Dimensionality used to prepare models were: (1, 3, 224, 224) however inputs are (64, 3, 224, 224)

I fixed the dimensionality to `(1, 3, 224, 224)` for the input pickle (`testing_input.p`) and repeats to `2` 

```
nohup python tritoninferenceissues/triton_inference.py resnet18 testing_input.p 2 outputs1.p &
nohup python tritoninferenceissues/triton_inference.py inceptionv3 testing_input.p 2 outputs5.p &
nohup python tritoninferenceissues/triton_inference.py resnet18 testing_input.p 2 outputs2.p &
nohup python tritoninferenceissues/triton_inference.py inceptionv3 testing_input.p 2 outputs6.p &
nohup python tritoninferenceissues/triton_inference.py resnet18 testing_input.p 2 outputs3.p &
nohup python tritoninferenceissues/triton_inference.py inceptionv3 testing_input.p 2 outputs7.p &
nohup python tritoninferenceissues/triton_inference.py resnet18 testing_input.p 2 outputs4.p &
nohup python tritoninferenceissues/triton_inference.py inceptionv3 testing_input.p 2 outputs8.p &
```

Script to prepare models:

```
import numpy as np
import pickle
input_data = np.ones((1, 3, 224, 224))
pickle.dump(input_data, open("testing_input.p", 'wb'))
```

Logging outputs:
```
import pickle
for i in range(1, 9):
    print(pickle.load(open("outputs" + str(i) + ".p", 'rb')))
```

```
[[-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]
 [-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]]
[[-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]
 [-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]]
[[-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]
 [-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]]
[[-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]
 [-0.03595  0.1165  -1.801   ... -1.518    0.1729   0.1812 ]]
[[ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]
 [ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]]
[[ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]
 [ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]]
[[ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]
 [ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]]
[[ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]
 [ 0.4512  0.4832 -0.525  ...  0.46    1.99    0.1752]]
```

**Comment by CoderHam** [comment]
@zmy1116 increasing the batch size to 64, the repeats to 16 and number of jobs for each model from 4 to 8 does not impact the results and we see there is no inconsistency in results. In short I am unable to reproduce your issue in 20.11 or master. 

Note: You must set the max_batch_size param during torch2trt to be able to run 64 batch size. Please repeat the experiment with the above fixes and re-open if needed.

**Comment by zmy1116** [comment]
@CoderHam  my bad, I put incorrect trt engine generation script here, the torch2trt lines are missing. However, I did produce the proper models for this experiments and saw the issues consistently.
 

That's said, I redid the full experiment from scratch and still seeing the issue:
 
step 1:  model conversions 
 ```
import torch
import torchvision
from torch2trt import torch2trt

# convert resnet18
model = torchvision.models.resnet18(pretrained=True).cuda().half().eval()
data = torch.randn((64, 3, 224, 224)).cuda().half()
model_trt = torch2trt(model, [data], fp16_mode=True, max_batch_size=64)
with open('/home/ubuntu/trt_issues_data/model_repository_2011/resnet18/1/model', "wb") as f:
    f.write(model_trt.engine.serialize())

# convert inception v3
model = torchvision.models.inception_v3(pretrained=True).cuda().half().eval()
data = torch.randn((64, 3, 224, 224)).cuda().half()
model_trt = torch2trt(model, [data], fp16_mode=True, max_batch_size=64)
with open('/home/ubuntu/trt_issues_data/model_repository_2011/inceptionv3/1/model', "wb") as f:
    f.write(model_trt.engine.serialize())
 ``` 
 
step 2: launch triton server 
 ```
 docker run -d --gpus=all --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v /home/ubuntu/trt_issues_data/model_repository_2011:/models -e CUDA_VISIBLE_DEVICES=0 nvcr.io/nvidia/tritonserver:20.11-py3 tritonserver --model-repository=/models --strict-model-config=false
 ```
 
step 3: generate inputs
```
import pickle
import numpy as np 
testing_inputs = np.ones([64, 3, 224, 224]).astype(np.float16)
pickle.dump(testing_inputs, open('/home/ubuntu/trt_issues_data/testing_inputs.p','wb'))
```
 
step 4: warmup GPU and triton server 
```
python /home/ubuntu/tritonissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs1.p
python /home/ubuntu/tritonissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs5.p
```
 
step 4: hammer the triton server with large load of jobs 
```
nohup python /home/ubuntu/tritonissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs1.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs5.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs2.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs6.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs3.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs7.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py resnet18 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs4.p &
nohup python /home/ubuntu/tritonissues/triton_inference.py inceptionv3 /home/ubuntu/trt_issues_data/testing_inputs.p 64 outputs8.p &
```

step 5: compare outputs 1-4 to outputs 5-8:
```
import numpy as np 
import pickle
f1 = pickle.load(open('/workspace/ubuntu/outputs1.p','rb'))
f2 = pickle.load(open('/workspace/ubuntu/outputs2.p','rb'))
f3 = pickle.load(open('/workspace/ubuntu/outputs3.p','rb'))
f4 = pickle.load(open('/workspace/ubuntu/outputs4.p','rb'))

f5 = pickle.load(open('/workspace/ubuntu/outputs5.p','rb'))
f6 = pickle.load(open('/workspace/ubuntu/outputs6.p','rb'))
f7 = pickle.load(open('/workspace/ubuntu/outputs7.p','rb'))
f8 = pickle.load(open('/workspace/ubuntu/outputs8.p','rb'))
for entry in [f2,f3,f4]:
    print('Max Error', np.max(np.abs(f1-entry)), 'Portion of outputs that are different', np.sum(np.abs(f1-entry) > 0.1)/ (4096*1000))
for entry in [f7,f6,f8]:
    print('Max Error', np.max(np.abs(f5-entry)), 'Portion of outputs that are different', np.sum(np.abs(f5-entry) > 0.1)/ (4096*1000))
```

printed outputs:
```
Max Error 3.484 Portion of outputs that are different 0.00022314453125
Max Error 3.484 Portion of outputs that are different 0.00022314453125
Max Error 3.484 Portion of outputs that are different 0.00022314453125
Max Error 26.17 Portion of outputs that are different 0.001660400390625
Max Error 12.89 Portion of outputs that are different 0.000716064453125
Max Error 12.89 Portion of outputs that are different 0.00102294921875
```

Now why you are not seeing the issues,  there can be two things :
1. We have to really push the GPU usage towards 100% to see the issue,  if the GPU was under used, we don't see the issues 
2. The discrepancy only occurs on a **small fraction of entries**.   You have to compare every entry of all outputs to see the issue.


Our company does works in video processing,  when we migrate to Triton Server recently we did not see the issue because out of say on an object detection task over 5000 frames, only ~30 frames results are off, and only few frames are significantly off. Only by luck last week I stomp on one of the really wrong result and find out there is this problem.

I cannot reopen the issue, let me know you have seen this msg,  or I will create a new bug separately

**Comment by CoderHam** [comment]
@zmy1116 thanks for your response. I have re-opened the ticket and will run the test with master comparing **all** output values like you have done above. There was a fix pushed in to the TRT backend: https://github.com/triton-inference-server/server/pull/2348 which may have fixed this issue.

**Comment by CoderHam** [comment]
20.11
```
Max Error 98.06 Portion of outputs that are different 0.000243896484375
Max Error 98.06 Portion of outputs that are different 0.000243896484375
Max Error 98.06 Portion of outputs that are different 0.000243896484375
Max Error 12.95 Portion of outputs that are different 0.000233642578125
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.9233 Portion of outputs that are different 0.000161376953125
```

In Master:
```
Max Error 12.62 Portion of outputs that are different 0.00023974609375
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 12.74 Portion of outputs that are different 0.00024462890625
Max Error 0.2295 Portion of outputs that are different 2.197265625e-05
Max Error 0.2295 Portion of outputs that are different 1.3671875e-05
```

Looks like the issue is still existent in master. Investigating the issue further.

**Comment by CoderHam** [comment]
@zmy1116  have you tried running the TRT models using the TRT APIs directly outside Triton?

**Comment by zmy1116** [comment]
@CoderHam  yes before migrating to Triton server we run trt model in python with something like this 
```
import numpy as np
import tensorrt as trt
import pycuda.autoinit
import pycuda.driver as cuda


# Simple helper data class that's a little nicer to use than a 2-tuple.
class HostDeviceMem(object):
    def __init__(self, host_mem, device_mem, raw_shape):
        self.host = host_mem
        self.device = device_mem
        self.raw_shape = raw_shape
        self.flatten_size = np.prod(self.raw_shape[1:])

    def __str__(self):
        return "Host:\n" + str(self.host) + "\nDevice:\n" + str(self.device)

    def __repr__(self):
        return self.__str__()

    def to_original_shape(self):
        return self.host.reshape(self.raw_shape)


# Allocates all buffers required for an engine, i.e. host/device inputs/outputs.
def allocate_buffers(engine):
    inputs = []
    outputs = []
    bindings = []
    stream = cuda.Stream()
    for binding in engine:
        size = trt.volume(engine.get_binding_shape(binding)) * engine.max_batch_size
        dtype = trt.nptype(engine.get_binding_dtype(binding))
        # Allocate host and device buffers
        host_mem = cuda.pagelocked_empty(size, dtype)
        device_mem = cuda.mem_alloc(host_mem.nbytes)
        # Append the device buffer to device bindings.
        bindings.append(int(device_mem))
        # Append to the appropriate list.
        raw_shape = [engine.max_batch_size] + list(engine.get_binding_shape(binding))
        if engine.binding_is_input(binding):
            inputs.append(HostDeviceMem(host_mem, device_mem, raw_shape))
        else:
            outputs.append(HostDeviceMem(host_mem, device_mem, raw_shape))
    return inputs, outputs, bindings, stream


def do_inference(context, bindings, inputs, outputs, stream, batch_size=1):
    # Transfer input data to the GPU.
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    # Run inference.
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    # Transfer predictions back from the GPU.
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    # Synchronize the stream
    stream.synchronize()
    # Return only the host outputs.
    return [out.to_original_shape()[:batch_size] for out in outputs]


class TRTInferenceModule(object):

    def __init__(self, model_type, engine_file):
        self.model_tyle = model_type
        # load engine, allocate context
        with open(engine_file, "rb") as f, trt.Logger() as logger, trt.Runtime(logger) as runtime:
            self.engine = runtime.deserialize_cuda_engine(f.read())
            self.context = self.engine.create_execution_context()

        self.inputs, self.outputs, self.bindings, self.stream = allocate_buffers(self.engine)
        self.max_batch_size = self.engine.max_batch_size

    def load_numpy_inputs(self, inputs_list):

        batch_size = inputs_list[0].shape[0]

        for idx, inputs in enumerate(inputs_list):
            inputs_flatten = inputs.flatten()
            input_host = self.inputs[idx].host
            if batch_size < self.max_batch_size:
                input_host = input_host[:batch_size * self.inputs[idx].flatten_size]
            else:
                input_host = self.inputs[idx].host
            np.copyto(input_host, inputs_flatten)

    def do_inference(self, inputs_list):

        # load input to gpu
        self.load_numpy_inputs(inputs_list)

        # inference
        batch_size = inputs_list[0].shape[0]
        outputs = do_inference(self.context, self.bindings, self.inputs, self.outputs, self.stream,
                               batch_size=batch_size)

        return outputs

```

I don't think we have seen issues runnint TensorRT model alone (one model running in one GPU)

**Comment by CoderHam** [comment]
After the fix from https://github.com/triton-inference-server/server/pull/2348 the issue is resolved. You can build a version of Tritonserver from master for your use case since it now contains the fix. Refer to the docs [here](https://github.com/triton-inference-server/server/blob/master/docs/build.md) for the same. 

```
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
Max Error 0.0 Portion of outputs that are different 0.0
```

**Comment by zmy1116** [comment]
@CoderHam Thank you for your help. Indeed building from the main branch (21.01dev), the problem is resolved.

Not really important: the published version (20.12) released on Dec 18 still have this issue. Since you answered me on Dec 16, I thought the fix should be already included in 20.12.

**Comment by philipp-schmidt** [comment]
Thanks @zmy1116 for the minimal example and @CoderHam for the fix. This was the exact behaviour I was describing in https://github.com/triton-inference-server/server/issues/2231#issuecomment-734373423. I can confirm it's resolved.

**Comment by huntrax11** [comment]
@CoderHam It looks like the issue still remains in the libtorch backend.

**Triton Information**
I built myself from main branch (9c7d24bf6bfbdb527a0599ede5e4832040189c9b)

**To Reproduce**
- step 1: model conversions
```python
import torch
import torchvision

# convert resnet18
model = torchvision.models.resnet18(pretrained=True).cuda().half().eval()
script = torch.jit.script(model)
script.save('model_repo/resnet18/0/resnet18.pt')


# convert resnet34
model = torchvision.models.resnet34(pretrained=True).cuda().half().eval()
script = torch.jit.script(model)
script.save('model_repo/resnet34/0/resnet34.pt')
```

<details><summary>config.pbtxt</summary>
<p>
 
```protobuf
name: "resnet18"
platform: "pytorch_libtorch"
max_batch_size: 16
default_model_filename: "resnet18.pt"
input [
  {
    name: "input__0"
    data_type: TYPE_FP16
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP16
    dims: [1000]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 10000
}
```
```protobuf
name: "resnet34"
platform: "pytorch_libtorch"
max_batch_size: 16
default_model_filename: "resnet34.pt"
input [
  {
    name: "input__0"
    data_type: TYPE_FP16
    format: FORMAT_NCHW
    dims: [3, 224, 224]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP16
    dims: [1000]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 10000
}
```
</p>
</details>

Refer [zmy1116's comment](https://github.com/triton-inference-server/server/issues/2339#issuecomment-747106662) for remaining steps.

```
Max Error 0.001953 Portion of outputs that are different 0.0
Max Error 0.001953 Portion of outputs that are different 0.0
Max Error 0.002441 Portion of outputs that are different 0.0
Max Error 0.003906 Portion of outputs that are different 0.0
Max Error 0.002441 Portion of outputs that are different 0.0
Max Error 0.001953 Portion of outputs that are different 0.0
```

**Comment by CoderHam** [comment]
@huntrax11  you should try with the traced model instead of scripted and confirm the same. Sometimes the scripted model does not perform as expected. Additionally check with the 20.12 release container.

**Comment by huntrax11** [comment]
@CoderHam Thanks for the fast reply.
I tried the same test with the traced model, but It didn't work properly.

```python
import torch
import torchvision

# convert resnet18
model = torchvision.models.resnet18(pretrained=True).cuda().half().eval()
example = torch.rand(4, 3, 224, 224).cuda().half()
module = torch.jit.trace(model, example)
module.save('model_repo/resnet18/0/resnet18.pt')

# convert resnet34
model = torchvision.models.resnet34(pretrained=True).cuda().half().eval()
example = torch.rand(4, 3, 224, 224).cuda().half()
module = torch.jit.trace(model, example)
module.save('model_repo/resnet34/0/resnet34.pt')
```
```
Max Error 0.001953 Portion of outputs that are different 0.0
Max Error 0.001953 Portion of outputs that are different 0.0
Max Error 0.001953 Portion of outputs that are different 0.0
Max Error 0.002441 Portion of outputs that are different 0.0
Max Error 0.003906 Portion of outputs that are different 0.0
Max Error 0.002441 Portion of outputs that are different 0.0 
```

**Comment by CoderHam** [comment]
@huntrax11  Can you confirm that the inputs to the model are FP32 and not FP64?
> Despite using FP16 (half) while preparing your models are you passing FP64 in testing_inputs.p

If you see the max error numbers report by the test script they are exactly the same (just re-ordered). I can re-open this ticket for now but from my earlier testing the issue was indeed fixed in master. (Apologies for the incorrect statement about it being in 20.12 since it was merged in after the 20.12 release)

**Comment by huntrax11** [comment]
@CoderHam I changed the input data type accordingly to the model. I sent the whole source code via mail so you can check.

**Comment by CoderHam** [comment]
@huntrax11 please repeat your experiments with the latest release and let me know if you still see this issue.

**Comment by huntrax11** [comment]
@CoderHam The issue still remains in NGC 21.02-py3.

**Comment by CoderHam** [comment]
@huntrax11 the issue does not exist in the NGC 21.12 releaseor master.
