### ISSUE TITLE
perf_analyzer failed

### ISSUE THREAD

**Issue by zirui** [triton-inference-server/server#2342]
**Description**
i test a bert model  with triton.httpclient, it works as expected,
but got below errows when i test with perf_analyzer:

```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using average latency

Request concurrency: 1
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: pinned buffer: failed to perform CUDA copy: device-side assert triggered
```

triton-server logs:
```
/tmp/pip-req-build-7anwsztg/aten/src/ATen/native/cuda/Indexing.cu:666: indexSelectLargeIndex: block: [142,0,0], thread: [127,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
```

**Triton Information**
What version of Triton are you using? : 20.11

Are you using the Triton container or did you build it yourself?
triton containter:
tritonserver: 20.11-py3
tritonserver:20.11-py3-clientsdk

**To Reproduce**
Steps to reproduce the behavior.
perf_analyzer -m my_model_pt -u 0.0.0.0:9000 

model: torschript model
model config:

```
platform: "pytorch_libtorch"
max_batch_size: 8
input [
    {
      name: "input__0"
      data_type: TYPE_INT64
      dims: [ 128 ]
    },
    {
      name: "input__1"
      data_type: TYPE_INT64
      dims: [ 128 ]
    },
    {
      name: "input__2"
      data_type: TYPE_INT64
      dims: [ 128 ]
    }
]
output [
    {
      name: "output__0"
      data_type: TYPE_FP32
      dims: [ 2 ]
    }
]
```

**Expected behavior**

perf_analyzer should return perfomance report of  my model

**Comment by zirui** [comment]
i test with my input data, then it works
```
perf_analyzer -m my_model_pt -u 0.0.0.0:9000  --input-data test.data
```
i seems that the test input generated by perf_analyzer cause the model crashed

**Comment by deadeyegoodwin** [comment]
By default perf_analyzer sends random data. As you have seen, some models fail for random inputs. perf_analyzer has a -z flag that you can use to send all-zeros data that will work for some models. As in your case, sometimes you need to send specific input data. perf_analyzer is working correctly, it cannot automatically determine the exact input required by a model.

**Comment by zirui** [comment]
> By default perf_analyzer sends random data. As you have seen, some models fail for random inputs. perf_analyzer has a -z flag that you can use to send all-zeros data that will work for some models. As in your case, sometimes you need to send specific input data. perf_analyzer is working correctly, it cannot automatically determine the exact input required by a model.

thanks for your reply!
i tried  perf_analyzer with -z flag, and it works

**Comment by debasishaimonk** [comment]
HI @deadeyegoodwin can u share me how does testdata looks like?
