### ISSUE TITLE
Not able to use GKE default driver with Triton Inference Server

### ISSUE THREAD

**Issue by jakepoz** [triton-inference-server/server#2386]
**Description**
We are trying to deploy the 20.09 version of triton inference server to GKE. We are on GKE version 1.16, which has NVIDIA driver 418.67.

In the docs, it states that `However, if you are running on Tesla (for example, T4 or any other Tesla board), you may use NVIDIA driver release 418.xx or 440.30. ` So I believe that we should be compatible, as we are on a T4 gpu. 

However, I get the following errors and am unable to start the inference server.

```
"found 1 GPUs supporting NVML metrics
" GPU 0: Tesla T4"
"Initializing Triton Inference Server"
" id: 'triton'"
" version: '2.3.0'"
" extensions: classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics"

"failed to allocate pinned system memory: CUDA driver version is insufficient for CUDA runtime version"
```

**Triton Information**
nvcr.io/nvidia/tritonserver:20.09-py3

Using the container.

**To Reproduce**
       command: ["tritonserver"]
          args: ["--http-port=8501", "--model-repository=gs://xxxx",
                 "--model-control-mode=none", # Don't poll to reload models dynamically
                 "--strict-readiness=true", # Only say you're ready when all models loaded
                 "--exit-on-error=true",
                 "--log-warning=true", "--log-error=true", "--log-info=true"]

**Expected behavior**
Expected that the server will start and use the GPU.

**Comment by jakepoz** [comment]
I was able to resolve the problem. The issue is that you cannot override the command to be "tritonserver", you must allow the nvidia entry script to start first, and load the compatibility layer.

This configuration worked:
```
args: [ "tritonserver"

"--http-port=8501", "--model-repository=gs://xxxx",
"--model-control-mode=none", # Don't poll to reload models dynamically
"--strict-readiness=true", # Only say you're ready when all models loaded
"--exit-on-error=true",
"--log-warning=true", "--log-error=true", "--log-info=true"]
```
