### ISSUE TITLE
PyTorch backend sometimes allocates input tensors on wrong GPU on multi-GPU systems

### ISSUE THREAD

**Issue by jjancsary** [triton-inference-server/server#2626]
**Description**
I'm observing a new issue in Triton 21.02 where serving PyTorch models on a node with 2 GPUs will eventually produce an error triggered inside libtorch. The behavior is not deterministic and the exact error depends on the timing, but typically a PyTorch operation will complain that not all of its argument tensors reside on the same GPU.

Below is one example:
`RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 1 (while checking arguments for cudnn_convolution)`

In this specific case, sending a follow-up request to Triton produced the following error message:
`INPUT__0: failed to perform CUDA copy: an illegal memory access was encountered`

It seems that there is a newly introduced bug in the CUDA memory management of Triton.

The problem is not specific to the particular model that triggered the above error. We tested using a different PyTorch model and got similar behavior.

The only way of working around the problem seems to be to pin the model to GPU 0 (using an instance_group). Interestingly, pinning the model to GPU 1 does not have the desired effect; the error will eventually still occur.

I have verified that this problem does not occur in Triton 20.12. I've looked a little at the PyTorch backend code to figure out what changes occurred since 20.12, and I don't see any that could cause this problem. My assumption is that the problem is in the core "server" repository code.

**Triton Information**
What version of Triton are you using?
21.02

Are you using the Triton container or did you build it yourself?
I'm using the official build off nvcr.io 

**To Reproduce**
Steps to reproduce the behavior.

It should be possible to reproduce this using any PyTorch model on a node with multiple GPUs. As the problem is not deterministic, it is sometimes necessary to send a few requests before the problem occurs (maybe a dozen or so, on my VM).

In case it matters, I'm including the output nvidia-smi below:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000001:00:00.0 Off |                    0 |
| N/A   29C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  On   | 00000002:00:00.0 Off |                    0 |
| N/A   30C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**

Memory of the input tensors should be allocated on the GPU that the model is being executed on. No illegal memory access should occur.

**Comment by CoderHam** [comment]
I think the issue is in the way the model was traced/scripted. Have you tried to run the model just on 1 GPU i.e. GPU1 and GPU0 independently? 
Sometimes the device id for the gets erroneously captured in the trace. 
It would be helpful if you could also share the model so that we can work on a repro of the same.

**Comment by jjancsary** [comment]
Thanks for getting back on this so quickly.

I know there are a lot of issues around how PyTorch models are scripted, including GPU assignment and such. However, in this particular case, I'm not sure this is the cause:

- I tested with two different models (completely separate code base). Both worked with 20.12, but not anymore with 21.02.
- I've tried to run the models exclusively on GPU0 or GPU1 independently (by specifying the GPU in an instance_group). As mentioned above, running on GPU0 only has the desired effect. However, running on GPU1 only works for the first few requests, and only then an error as shown above occurs.
- Presumably the error message "failed to perform CUDA copy: an illegal memory access was encountered" hints at a real problem. I don't think this would occur just because the TorchScript model was traced to run on a particular GPU.

Unfortunately, the models that I tested with are proprietary, I cannot just share them without further ado. I would expect that the issue can be reproduced with publicly available models. If not, I'll need to invest some time to simplify our model code to a point where I can share it.


Looking at the code of the PyTorch backend again, are you sure that the following line of code is safe?
https://github.com/triton-inference-server/pytorch_backend/blob/fb989b1ca89436498c74988e9414e583962622c7/src/libtorch.cc#L667

It seems that the allocated backend memory for the inputs is unconditionally deleted, even if it was allocated from a pool (BackendMemory::AllocationType::GPU_POOL), the purpose of which is presumably to reuse the memory?

**Comment by jjancsary** [comment]
Here is another data point - **unable to reproduce** the problem with the following simplified setup:

- Trivial model consisting just of a single linear layer
- Model **scripted** (exported) inside nvcr.io/nvidia/pytorch:21.02-py3
- Model served via nvcr.io/nvidia/tritonserver:21.02-py3
- Requests sent via perf_client

In this particular case, everything works without pinning the model to GPU0.
Not sure what to make of it. Of course, this isn't proof either that there isn't a problem lurking somewhere.

**Comment by CoderHam** [comment]
@jjancsary thanks for running these tests. Since the minimal model you tested worked fine I feel like the issue lies elsewhere. 
Are you running one or multiple instances on the same GPU?
Would it be possible to share the model you are using or a minimal version of it that displays this issue?
In general the model should either not run at all or run successfully for all inferences. I wonder why it works for the first few requests (not just first request right?) but fails for subsequent requests.

**Comment by jjancsary** [comment]
@CoderHam, I tend to agree. Something definitely changed in the overall software stack, but meanwhile, I'm less convinced that the problem is in the Triton code specifically. The "failed to perform CUDA copy: an illegal memory access was encountered" seems to happen inside of PyTorch.
As I mentioned, the models are proprietary. I need to check back to see if and in which form we can share them. Another option is for me to try and reproduce the issue with a model that's publicly available. I'll let you know when I have something to share. In the meantime, thanks a lot for your help with this!

**Comment by jjancsary** [comment]
I have an update: The issue seems to be in PyTorch.

I'm using the following code to feed our model and run it on GPU 1 (excuse my poor Python):
```
import torch
import random

device = torch.device("cuda:1")
loaded = torch.jit.load('model.pt', map_location=device)

i = 0
while i < 1024:
    nsamp = random.randrange(16000, 30*16000)
    samples = torch.rand((1, nsamp), device=device)
    nsamples = torch.tensor([[nsamp]], device=device)
    print("running with %s samples" % nsamp)
    loaded.forward(samples, nsamples)
    i = i +1
```
Running via: nvidia-docker run nvcr.io/nvidia/pytorch:**20.12**-py3
_Succeeds_

Running via nvidia-docker run nvcr.io/nvidia/pytorch:**21.02**-py3
_Fails_
`RuntimeError: arguments are located on different GPUs at /tmp/pip-req-build-_tx3iysr/aten/src/THC/generic/THCTensorMasked.cu:27`

It seems that in 21.02, not all tensors are correctly mapped to GPU1 ("cuda:1").

Consequently, this is not a problem in the Triton code; but, to some extent, possibly still a problem in "Triton the container".
Not sure how to proceed from here. One last thing that comes to mind is that we can try to re-export our TorchScript models using different PyTorch versions. In principle, PyTorch claims backwards compatibility, but who knows.

**Comment by ptrblck** [comment]
@jjancsary Thanks for the minimal code snippet.
Were you scripting or tracing the original model before saving it? Also, which device was used before saving it?

**Comment by jjancsary** [comment]
Hi @ptrblck, 

The particular model used in the small example above was exported through a combination of tracing and scripting (the parts that depend on input length have been scripted). It's been exported on CPU.  Note that we've used this model successfully prior to the 21.02 build, and it seems to work flawlessly with  pytorch:1.8.0-cuda11.1 as well.

Besides, we have another model that shows the same symptoms. It's a completely separate code base (machine translation based on transformer) and based on the FairSeq library.

**Comment by omerbenamram** [comment]
Just to chime in - experiencing exactly the same issue, which was not present when using the exact same model with `r20.12`.
We ended up spinning a triton container for each GPU (with `CUDA_VISIBLE_DEVICES`) and round robin the GRPC requests between them. This clearly isn't ideal but it works for our use case.

We're using torchscript only - so there shouldn't be any issues regarding tracing the code to use GPU0 only.

**Comment by ptrblck** [comment]
Thanks for the followup.
Unfortunately, we don't have enough information to reproduce the issue using:
```python
# save.py
import torch
import torch.nn as nn
import torchvision.models as models

model = models.resnet152()
model = torch.jit.script(model)

torch.jit.save(model, 'model.pt')

# repro.py
import torch
import torch.nn as nn
import random

device = 'cuda:1'
loaded = torch.jit.load('model.pt', map_location=device)

i = 0
while i < 1024:
    x = torch.randn(random.randint(1, 64), 3, 224, 224, device=device)
    out = loaded(x)
    i = i + 1
print('done')
```
in 21.02. 
Could you post an executable code snippet to reproduce this error?

**Comment by jjancsary** [comment]
Hi,

We've tried the following in the meantime:

- Export our PyTorch models directly in `nvcr.io/nvidia/pytorch:21.02-py3` (previously exported using PyTorch 1.7):
  - No effect (problem persists)

- Reproduce the problem using publicly available models (from huggingface transformers library):
  - No difference between `nvcr.io/nvidia/pytorch:21.02-py3` and `pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel`
  - Some models work on `cuda:1` after tracing and some don't, but no difference between the above two containers

The fact remains that there is a difference in behavior between `nvcr.io/nvidia/pytorch:21.02-py3` and `pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel` for two of our models, the code of which I cannot share unfortunately.

@omerbenamram - are your models proprietary as well, or would you be able to share the code with the NVIDIA team?

At this point, I'm tempted to wait and see if the problem will "just go away" with `nvcr.io/nvidia/pytorch:21.03-py3`.

**Comment by jjancsary** [comment]
Hi,

I have good news: At least according to some early experiments, the issue seems to be gone with the latest NGC images.
I've tested `nvcr.io/nvidia/pytorch:21.03-py3` directly and `nvcr.io/nvidia/tritonserver:21.03-py3` as well.

**Comment by deadeyegoodwin** [comment]
Closing,
