### ISSUE TITLE
Golang GRPC Request caused Triton server with a fatal error

### ISSUE THREAD

**Issue by sunhailin-Leo** [triton-inference-server/server#2706]
**Description**
I use golang grpc client to request the server. But i meet a fatal error, cause triton server is dead.
My example is refer here: https://github.com/triton-inference-server/server/blob/master/src/clients/go/grpc_simple_client.go 

```bash
I0407 11:04:08.133477 51878 pinned_memory_manager.cc:131] pinned memory allocation: size 128, addr 0x7f747c0003f0
I0407 11:04:08.133506 51878 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 25 step ISSUED
I0407 11:04:08.133603 51878 pinned_memory_manager.cc:131] pinned memory allocation: size 128, addr 0x7f747c000480
I0407 11:04:08.133605 51878 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 25 step COMPLETE
I0407 11:04:08.133638 51878 pinned_memory_manager.cc:131] pinned memory allocation: size 128, addr 0x7f747c000510
I0407 11:04:08.133669 51878 grpc_server.cc:2139] Done for ModelInferHandler, 25
I0407 11:04:08.133705 51878 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HN_0_0_gpu0
E0407 11:04:08.133772 51878 logging.cc:43] safeContext.cpp (184) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E0407 11:04:08.133826 51878 logging.cc:43] FAILED_EXECUTION: std::exception
I0407 11:04:08.133844 51878 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
```

**Model**
My Model is using TensorRT plan (Bert)

**Triton Version**
21.03

**Comment by CoderHam** [comment]
The issue is arising inside the TRT model. 
Which CUDNN / Cuda version was the TRT model prepared for?
Does the TRT model run successfully outside Triton?

**Comment by sunhailin-Leo** [comment]
@CoderHam 
* TRT model using by HTTP is ok, but Golang GRPC is arising the error.

**Comment by CoderHam** [comment]
Which version of GRPC are you using? 
To clarify the TRT model in the production environment works for HTTP but not GRPC? 
And you are running the Triton 21.03 NGC container?

**Comment by sunhailin-Leo** [comment]
> Which version of GRPC are you using?
> To clarify the TRT model in the production environment works for HTTP but not GRPC?
> And you are running the Triton 21.03 NGC container?

```bash
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0-devel
// 	protoc        v3.15.7
// source: grpc_service.proto
```

* This problem is solved, is my mistake. I sending the wrong data in `ModelInferRequest`, which caused the model to infer data error.

**Comment by sunhailin-Leo** [comment]
@CoderHam 
* I met this problem again in GRPC. I was using Triton 21.03 NGC container

**Comment by CoderHam** [comment]
@sunhailin-Leo can you share the server logs for the above error? Can you also confirm that the docker was run with necessary access to the GPU?

**Comment by sunhailin-Leo** [comment]
@CoderHam 
* Sorry for too late to reply your Q&A.
* I was confirmed my trtion is run on the GPU, because it was run on k8s with nvidia-docker and nvidia-gpu-plugin.
* Here is my server logs
```
I0913 03:13:38.444469 1 plan_backend.cc:2423] Running bert-HB_0_0_gpu1 with 1 requests
I0913 03:13:38.444494 1 plan_backend.cc:3336] Optimization profile 0 [0] is selected for bert-HB_0_0_gpu1
I0913 03:13:38.444514 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa78402fe40
I0913 03:13:38.444538 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa78402ff10
I0913 03:13:38.444550 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa78402ffe0
I0913 03:13:38.444564 1 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HB_0_0_gpu1
I0913 03:13:38.444788 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78405f4a0
I0913 03:13:38.444800 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78405f6b0
I0913 03:13:38.444809 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1316 step ISSUED
I0913 03:13:38.444819 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.444902 1 grpc_server.cc:2265] GRPC free: size 512, addr 0x7f957c000bd0
I0913 03:13:38.444913 1 grpc_server.cc:2265] GRPC free: size 193608, addr 0x7f98827ab460
I0913 03:13:38.444971 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.444984 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1315 step COMPLETE
I0913 03:13:38.445003 1 grpc_server.cc:2139] Done for ModelInferHandler, 1315
I0913 03:13:38.444988 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa7840004a0
I0913 03:13:38.445033 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402fca0
I0913 03:13:38.445043 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402fd70
I0913 03:13:38.445193 1 infer_response.cc:139] add response output: output: embedding, type: FP32, shape: [1,128,1,1]
I0913 03:13:38.445208 1 grpc_server.cc:2219] GRPC: unable to provide 'embedding' in GPU, will use CPU
I0913 03:13:38.445216 1 grpc_server.cc:2230] GRPC: using buffer for 'embedding', size: 512, addr: 0x7f958404ce70
I0913 03:13:38.445225 1 pinned_memory_manager.cc:131] pinned memory allocation: size 512, addr 0x7fa7840300b0
I0913 03:13:38.445241 1 infer_response.cc:139] add response output: output: probability, type: FP32, shape: [1,48402,1,1]
I0913 03:13:38.445250 1 grpc_server.cc:2219] GRPC: unable to provide 'probability' in GPU, will use CPU
I0913 03:13:38.445292 1 grpc_server.cc:2230] GRPC: using buffer for 'probability', size: 193608, addr: 0x7f9584090f40
I0913 03:13:38.445301 1 pinned_memory_manager.cc:131] pinned memory allocation: size 193608, addr 0x7fa7840302c0
I0913 03:13:38.445431 1 grpc_server.cc:2265] GRPC free: size 512, addr 0x7f958404dbd0
I0913 03:13:38.445440 1 grpc_server.cc:2265] GRPC free: size 193608, addr 0x7f95800c4fb0
I0913 03:13:38.445487 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.445491 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1316 step COMPLETE
I0913 03:13:38.445498 1 grpc_server.cc:2139] Done for ModelInferHandler, 1316
I0913 03:13:38.445500 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000780
I0913 03:13:38.445507 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000300
I0913 03:13:38.445513 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa7840003d0
I0913 03:13:38.445988 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa7840300b0
I0913 03:13:38.446005 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa7840302c0
I0913 03:13:38.446016 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1317 step ISSUED
I0913 03:13:38.446028 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.446658 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1318 step START
I0913 03:13:38.446668 1 grpc_server.cc:3082] New request handler for ModelInferHandler, 1319
I0913 03:13:38.446672 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.446678 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.446686 1 grpc_server.cc:2265] GRPC free: size 512, addr 0x7f958404ce70
I0913 03:13:38.446696 1 grpc_server.cc:2265] GRPC free: size 193608, addr 0x7f9584090f40
I0913 03:13:38.446692 1 infer_request.cc:502] prepared: [0x0x7fa6240155d0] request id: , model: bert-HB, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fa624008158] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62401d028] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624014078] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
override inputs:
inputs:
[0x0x7fa624014078] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62401d028] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624008158] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
original requested outputs:
embedding
probability
requested outputs:
embedding
probability

I0913 03:13:38.446750 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.446753 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1317 step COMPLETE
I0913 03:13:38.446766 1 grpc_server.cc:2139] Done for ModelInferHandler, 1317
I0913 03:13:38.446767 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402fe40
I0913 03:13:38.446784 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402ff10
I0913 03:13:38.446790 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402ffe0
I0913 03:13:38.446821 1 plan_backend.cc:2423] Running bert-HB_0_0_gpu0 with 1 requests
I0913 03:13:38.446834 1 plan_backend.cc:3336] Optimization profile 0 [0] is selected for bert-HB_0_0_gpu0
I0913 03:13:38.446848 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000780
I0913 03:13:38.446866 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000300
I0913 03:13:38.446875 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa7840003d0
I0913 03:13:38.446887 1 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HB_0_0_gpu0
I0913 03:13:38.447399 1 infer_response.cc:139] add response output: output: embedding, type: FP32, shape: [1,128,1,1]
I0913 03:13:38.447412 1 grpc_server.cc:2219] GRPC: unable to provide 'embedding' in GPU, will use CPU
I0913 03:13:38.447418 1 grpc_server.cc:2230] GRPC: using buffer for 'embedding', size: 512, addr: 0x7f957c081e70
I0913 03:13:38.447424 1 pinned_memory_manager.cc:131] pinned memory allocation: size 512, addr 0x7fa78402fca0
I0913 03:13:38.447438 1 infer_response.cc:139] add response output: output: probability, type: FP32, shape: [1,48402,1,1]
I0913 03:13:38.447446 1 grpc_server.cc:2219] GRPC: unable to provide 'probability' in GPU, will use CPU
I0913 03:13:38.447489 1 grpc_server.cc:2230] GRPC: using buffer for 'probability', size: 193608, addr: 0x7f98827ab460
I0913 03:13:38.447497 1 pinned_memory_manager.cc:131] pinned memory allocation: size 193608, addr 0x7fa78402feb0
I0913 03:13:38.448303 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402fca0
I0913 03:13:38.448314 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa78402feb0
I0913 03:13:38.448324 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1318 step ISSUED
I0913 03:13:38.448336 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.448949 1 grpc_server.cc:2265] GRPC free: size 512, addr 0x7f957c081e70
I0913 03:13:38.448956 1 grpc_server.cc:2265] GRPC free: size 193608, addr 0x7f98827ab460
I0913 03:13:38.449006 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.449016 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1318 step COMPLETE
I0913 03:13:38.449022 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000780
I0913 03:13:38.449022 1 grpc_server.cc:2139] Done for ModelInferHandler, 1318I0913 03:13:38.449038 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000300
I0913 03:13:38.449049 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa7840003d0

I0913 03:13:38.449431 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000570
I0913 03:13:38.449447 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000850
I0913 03:13:38.449456 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1291 step ISSUED
I0913 03:13:38.449470 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.450219 1 grpc_server.cc:2265] GRPC free: size 512, addr 0x7f9580095df0
I0913 03:13:38.450229 1 grpc_server.cc:2265] GRPC free: size 193608, addr 0x7f957c094520
I0913 03:13:38.450287 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.450293 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1291 step COMPLETE
I0913 03:13:38.450301 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000090
I0913 03:13:38.450302 1 grpc_server.cc:2139] Done for ModelInferHandler, 1291I0913 03:13:38.450311 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000160

I0913 03:13:38.450320 1 pinned_memory_manager.cc:158] pinned memory deallocation: addr 0x7fa784000230
I0913 03:13:38.479623 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1319 step START
I0913 03:13:38.479639 1 grpc_server.cc:3082] New request handler for ModelInferHandler, 1320
I0913 03:13:38.479645 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.479650 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.479684 1 infer_request.cc:502] prepared: [0x0x7fa62400d710] request id: , model: bert-HB, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fa62401d168] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62400fcb8] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62401aad8] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
override inputs:
inputs:
[0x0x7fa62401aad8] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62400fcb8] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62401d168] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
original requested outputs:
embedding
probability
requested outputs:
embedding
probability

I0913 03:13:38.479812 1 plan_backend.cc:2423] Running bert-HB_0_0_gpu3 with 1 requests
I0913 03:13:38.479840 1 plan_backend.cc:3336] Optimization profile 0 [0] is selected for bert-HB_0_0_gpu3
I0913 03:13:38.479857 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000090
I0913 03:13:38.479876 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1319 step ISSUED
I0913 03:13:38.479942 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000160
I0913 03:13:38.479942 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1319 step COMPLETE
I0913 03:13:38.479956 1 grpc_server.cc:2139] Done for ModelInferHandler, 1319I0913 03:13:38.479955 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000230

I0913 03:13:38.479967 1 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HB_0_0_gpu3
E0913 03:13:38.480074 1 logging.cc:43] safeContext.cpp (184) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E0913 03:13:38.480170 1 logging.cc:43] FAILED_EXECUTION: std::exception
I0913 03:13:38.480181 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.480681 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1320 step START
I0913 03:13:38.480691 1 grpc_server.cc:3082] New request handler for ModelInferHandler, 1321
I0913 03:13:38.480697 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.480701 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.480712 1 infer_request.cc:502] prepared: [0x0x7fa62400d310] request id: , model: bert-HB, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fa624010f58] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624016708] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62400ef88] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
override inputs:
inputs:
[0x0x7fa62400ef88] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624016708] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624010f58] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
original requested outputs:
embedding
probability
requested outputs:
embedding
probability

I0913 03:13:38.480829 1 plan_backend.cc:2423] Running bert-HB_0_0_gpu1 with 1 requests
I0913 03:13:38.480906 1 plan_backend.cc:3336] Optimization profile 0 [0] is selected for bert-HB_0_0_gpu1
I0913 03:13:38.480955 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000300
I0913 03:13:38.480992 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1320 step ISSUED
I0913 03:13:38.481198 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa7840003d0
I0913 03:13:38.481200 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1320 step COMPLETE
I0913 03:13:38.481215 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa7840004a0
I0913 03:13:38.481229 1 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HB_0_0_gpu1
I0913 03:13:38.481230 1 grpc_server.cc:2139] Done for ModelInferHandler, 1320
E0913 03:13:38.481276 1 logging.cc:43] safeContext.cpp (184) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E0913 03:13:38.481317 1 logging.cc:43] FAILED_EXECUTION: std::exception
I0913 03:13:38.481327 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.481424 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1321 step START
I0913 03:13:38.481434 1 grpc_server.cc:3082] New request handler for ModelInferHandler, 1322
I0913 03:13:38.481439 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.481443 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.481454 1 infer_request.cc:502] prepared: [0x0x7fa624012430] request id: , model: bert-HB, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fa624016348] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa6240135e8] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624013728] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
override inputs:
inputs:
[0x0x7fa624013728] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa6240135e8] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624016348] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
original requested outputs:
embedding
probability
requested outputs:
embedding
probability

I0913 03:13:38.481543 1 plan_backend.cc:2423] Running bert-HB_0_0_gpu0 with 1 requests
I0913 03:13:38.481581 1 plan_backend.cc:3336] Optimization profile 0 [0] is selected for bert-HB_0_0_gpu0
I0913 03:13:38.481601 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000570
I0913 03:13:38.481613 1 grpc_server.cc:3240] ModelInferHandler::InferResponseComplete, 1321 step ISSUED
I0913 03:13:38.481677 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1321 step COMPLETE
I0913 03:13:38.481678 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000640
I0913 03:13:38.481690 1 grpc_server.cc:2139] Done for ModelInferHandler, 1321
I0913 03:13:38.481701 1 pinned_memory_manager.cc:131] pinned memory allocation: size 192, addr 0x7fa784000710
I0913 03:13:38.481708 1 plan_backend.cc:2838] Context with profile 0 [0] is being executed for bert-HB_0_0_gpu0
E0913 03:13:38.481723 1 logging.cc:43] safeContext.cpp (184) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E0913 03:13:38.481745 1 logging.cc:43] FAILED_EXECUTION: std::exception
I0913 03:13:38.481753 1 grpc_server.cc:2817] ModelInferHandler::InferRequestComplete
I0913 03:13:38.482802 1 grpc_server.cc:3089] Process for ModelInferHandler, rpc_ok=1, 1322 step START
I0913 03:13:38.482812 1 grpc_server.cc:3082] New request handler for ModelInferHandler, 1323
I0913 03:13:38.482816 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.482822 1 model_repository_manager.cc:656] GetInferenceBackend() 'bert-HB' version 1
I0913 03:13:38.482831 1 infer_request.cc:502] prepared: [0x0x7fa62400ca10] request id: , model: bert-HB, requested version: 1, actual version: 1, flags: 0x0, correlation id: 0, batch size: 1, priority: 0, timeout (us): 0
original inputs:
[0x0x7fa624006b08] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624015c78] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa62400ea98] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
override inputs:
inputs:
[0x0x7fa62400ea98] input: segment_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624015c78] input: input_ids, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
[0x0x7fa624006b08] input: input_mask, type: INT32, original shape: [1,48], batch + shape: [1,48], shape: [48]
original requested outputs:
embedding
probability
requested outputs:
embedding
probability
```

**Comment by sunhailin-Leo** [comment]
@CoderHam 
* This problem did not appear at the beginning, but during the pressure test of my service.

**Comment by CoderHam** [comment]
@GuanLuo / @tanmayv25 do you have an idea of what might cause this cudnn error?

**Comment by tanmayv25** [comment]
The BERT model is very sensitive to data. I have seen similar error popping up when using incorrect data in input tensors.
https://github.com/triton-inference-server/server/issues/745

@sunhailin-Leo  Can you confirm your pressure test is indeed sending the valid data to the server?

**Comment by CoderHam** [comment]
Closing due to inactivity.
