### ISSUE TITLE
Driver incompatibility for triton image on sagemaker instance

### ISSUE THREAD

**Issue by lminer** [triton-inference-server/server#3813]
I'm trying to get an image based off `nvcr.io/nvidia/tritonserver:21.12-tf2-python-py3` to run on a sagemaker instance of type: `ml.g4dn.xlarge`.  Unfortunately, I'm getting the following error pointing to issues with driver incompatibility:

```
2022-01-14 21:39:05.231391: I tensorflow/cc/saved_model/loader.cc:303] SavedModel load for tags { serve };
Status: fail: Internal: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version. 
Took 429951 microseconds.
```

From what I can tell, the sagemaker instance is on version `440.33.01`. The compatibility matrix appears to suggest that it should be compatible:

```
Release 21.12 is based on NVIDIA CUDA 11.5.0, which requires NVIDIA Driver release 495 or later. 
However, if you are running on a Data Center GPU (for example, T4 or any other Tesla board), 
you may use NVIDIA driver release 418.40 (or later R418), 440.33 (or later R440), 450.51 (or later R450), 
460.27 (or later R460), or 470.57 (or later R470). The CUDA driver's compatibility package 
only supports particular drivers.
```

Is this information incorrect, and if not, what version would be compatible?

**Comment by lminer** [comment]
I tried using the image for `21.03`, which comes with cuda 11.1 and so should be compatible, but it still errored out. This time the error is as follows:

```E0115 23:38:07.125420 9 server.cc:181] Failed to initialize CUDA memory manager: unable to get number of CUDA devices: initialization error```

**Comment by deadeyegoodwin** [comment]
What is the console output when the container is started?

**Comment by lminer** [comment]
Turns out it was an env var issue. I added this to my dockerfile and now it works: 
```
ENV LD_LIBRARY_PATH="/usr/local/cuda/compat/lib.real:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:${LD_LIBRARY_PATH}"
```
