### ISSUE TITLE
Graceful handing of oom errors

### ISSUE THREAD

**Issue by ssrothman** [triton-inference-server/server#4023]
**Is your feature request related to a problem? Please describe.**
If a Triton server is fulfilling inference requests from several threads or several processes, this can sometimes overwhelm the available gpu memory. The current behavior when this happens is that the server prints an oom error and crashes. Eg: 

`2022-03-08 19:50:57.703709351 [E:onnxruntime:, sequential_executor.cc:339 Execute] Non-zero status code returned while running Conv node. Name:'StatefulPartitionedCall/model/convOneParticle/conv1d' Status Message: /workspace/onnxruntime/onnxruntime/core/framework/bfc_arena.cc:330 void* onnxruntime::BFCArena::AllocateRawInternal(size_t, bool) Failed to allocate memory for requested buffer of size 54566400`

Then all of the other processes being served by that server will also crash, as they are trying to talk to a service that no longer exists. 

**Describe the solution you'd like**
Instead of taking down the server and therefore every other process that depends on it, the desired behavior when a Triton client asks for too much memory would be for the failure to happen on the client end. Ideally the Triton server would catch the OOM error, abort that individual inference request, and send back to the offending client some sort of error code. The client could then catch this error and know to either wait a little bit (ie until the memory load from other inference requests has died down a bit) or otherwise reduce the size of its inference request. Even if the client were not to catch this error, only that single client process would crash, and it wouldn't be able to take down the server and every other client connected to it. 

**Describe alternatives you've considered**
The only alternative I have right now is to substantially reduce the size of each individual inference request so as to avoid the possibility of overwhelming the available server memory. 

**Additional context**
NA

**Comment by rmccorm4** [comment]
Thanks for submitting this issue @ssrothman .

@GuanLuo @tanmayv25 any thoughts on this? Do we generally know available memory (whether GPU or CPU) in advance when requesting an allocation to handle this?

**Comment by ssrothman** [comment]
Hi, I switched to a more recent server version (I went from server_version=2.11.0 to server_version=2.15.0) and the exact behavior I want seems to have already been implemented: the oom errors are being caught by the server and thrown back at the client. If you confirm that I'm understanding this more recent functionality we can probably close this issue. Sorry about that!

**Comment by tanmayv25** [comment]
@ssrothman  I believe this issue was fixed by this PR: https://github.com/triton-inference-server/onnxruntime_backend/pull/71
