### ISSUE TITLE
perf_analyzer failed with --shared-memory=cuda

### ISSUE THREAD

**Issue by ZJU-lishuang** [triton-inference-server/server#4127]
**Description**
When using `--shared-memory cuda` in perf_analyzer.like
```
perf_analyzer -m yolov5 --concurrency-range 2 --shared-memory cuda
```
I met this error.
`error: failed to create concurrency manager: unable to allocate memory of 8568000 bytes on gpu for output output : CUDA driver version is insufficient for CUDA runtime version`

**Triton Information**
I have tried following docker.
nvcr.io/nvidia/tritonserver:21.08-py3 and nvcr.io/nvidia/tritonserver:21.08-py3-sdk
nvcr.io/nvidia/tritonserver:21.11-py3 and nvcr.io/nvidia/tritonserver:21.11-py3-sdk

Are you using the Triton container or did you build it yourself?
using the Triton container

**To Reproduce**
my computer
GPU: NVIDIA GeForce RTX 3070 Laptop

nvidia driver:
![2022-03-29 20-06-41屏幕截图](https://user-images.githubusercontent.com/26588466/160607630-74dbfb3d-3999-4de4-9345-3669f7993eed.png)
**I have tried both 470 and 510**

Steps to reproduce the behavior.
triton server 
```
sudo docker run --gpus "device=0" --name tritonserver-21.08 --rm \
--net=host --ipc=host --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
-v$(pwd)/triton-deploy/model_nonms:/models \
nvcr.io/nvidia/tritonserver:21.08-py3 tritonserver --model-repository=/models \
--strict-model-config=true --grpc-infer-allocation-pool-size=16 --log-verbose=1
```

triton client
```
sudo docker run -it --rm --net=host --shm-size=1g --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 \
-v$(pwd)/yolov5_client:/workspace/yolov5_client nvcr.io/nvidia/tritonserver:21.08-py3-sdk
```

run the perf_analyzer
```
perf_analyzer -m yolov5 --concurrency-range 2 --shared-memory cuda
```
```

**Expected behavior**
perf_analyzer work well with `--shared-memory cuda`

**Comment by CoderHam** [comment]
@ZJU-lishuang the sdk container is being run without access to a GPU (No `--gpus` flag). It will be unable to create the cuda shared memory to be registered with Triton server.

**Comment by GuanLuo** [comment]
After the docker run change that @CoderHam mentioned you can verify if you can access the GPU via `nvidia-smi`

**Comment by ZJU-lishuang** [comment]
The problem is solved by the flag like `--gpus=all`.
