### ISSUE TITLE
Python backend stuck at TRITONBACKEND_ModelInstanceInitialize

### ISSUE THREAD

**Issue by huangyz0918** [triton-inference-server/server#4331]
**Description**
I wanna start the python backend following the example. But the container stucks at 

```bash
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.04 (build 36821869)
Triton Server Version 2.21.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .

WARNING: [Torch-TensorRT] - Unable to read CUDA capable devices. Return status: 35
I0504 12:25:52.440894 1 libtorch.cc:1381] TRITONBACKEND_Initialize: pytorch
I0504 12:25:52.441090 1 libtorch.cc:1391] Triton TRITONBACKEND API version: 1.9
I0504 12:25:52.441100 1 libtorch.cc:1397] 'pytorch' TRITONBACKEND API version: 1.9
W0504 12:25:52.441171 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I0504 12:25:52.441209 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
I0504 12:25:52.442350 1 model_repository_manager.cc:1077] loading: resnet:1
I0504 12:25:52.547089 1 python.cc:1769] Using Python execution env /models/resnet/../my-pytorch.tar.gz
I0504 12:25:52.547228 1 python.cc:2054] TRITONBACKEND_ModelInstanceInitialize: resnet_0 (CPU device 0)
```
My machine dose not have GPU. The confg 

```
name: "resnet"
backend: "python"

input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ -1, 3, 224, 224 ]
  }
]

output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1, 1000 ]
  }
]

instance_group [{
  count: 1
  kind: KIND_CPU
}]

parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/../my-pytorch.tar.gz"}
}

```
**Triton Information**
nvcr.io/nvidia/tritonserver:22.04-pyt-python-py3

**Are you using the Triton container or did you build it yourself?**
docker container

**Comment by huangyz0918** [comment]
I found the reason, when you start the docker container, you need to use `--shm-size=1g --ulimit memlock=-1` to increase the cpu resources that can be used by docker. The container supposed to throw the error rather than stuck at some logs.

**Comment by rmccorm4** [comment]
@Tabrizian do you know why the pinned memory manager is emitting a CUDA-related error here? Seems misleading.

**Comment by rmccorm4** [comment]
@huangyz0918 is this the full log/output? Can you share the full exact `docker run ...` command and the full `tritonserver --model-repository ...` command you ran to reproduce the issue?

CC @Tabrizian

**Comment by huangyz0918** [comment]
The original docker script, I ran this on an AWS EC2 instance only contains CPUs.

```bash
#!/usr/bin/env bash
docker run --rm -p8900:8000 -p8901:8001 -p8902:8002 \
  -v${PWD}/../example/pytorch/resnet:/models/resnet/ \
  -v${PWD}/../example/pytorch/my-pytorch.tar.gz:/models/my-pytorch.tar.gz \
  nvcr.io/nvidia/tritonserver:22.04-pyt-python-py3 tritonserver --model-repository=/models
```

After chaning to this, the server works,


```bash
#!/usr/bin/env bash
docker run --rm -p8900:8000 -p8901:8001 -p8902:8002 \
  --shm-size=1g --ulimit memlock=-1 \
  -v${PWD}/../example/pytorch/resnet:/models/resnet/ \
  -v${PWD}/../example/pytorch/my-pytorch.tar.gz:/models/my-pytorch.tar.gz \
  nvcr.io/nvidia/tritonserver:22.04-pyt-python-py3 tritonserver --model-repository=/models
```

**Comment by GuanLuo** [comment]
@Tabrizian I thought Python backend would return error if there is no enough shared memory available for initialization?

**Comment by Tabrizian** [comment]
I tried a small example locally and it did return an error if there wasn't enough shared memory. @rmccorm4 Could you please file a ticket for this issue so that I can take a closer look? Thanks.

**Comment by rmccorm4** [comment]
@Tabrizian filed DLIS-3765

**Comment by mikelam92** [comment]
We encounter the same issue, it stuck at loading model without returning an error. How can we properly diagnose? Thanks

**Comment by gandharv-kapoor** [comment]
@Tabrizian seeing the same issue and unable to find any specific issue even from verbose logs. Even tried @huangyz0918 workaround but that didnt help either. Can you suggest a solution or possible workaround? This is blocking us from making any progress.
```


=============================
--
Sun, May 29 2022 2:12:15 am | == Triton Inference Server ==
Sun, May 29 2022 2:12:15 am | =============================
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | NVIDIA Release 22.01 (build 31237563)
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | Various files include modifications (c) NVIDIA CORPORATION. All rights reserved.
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
Sun, May 29 2022 2:12:15 am | By pulling and using the container, you accept the terms and conditions of this license:
Sun, May 29 2022 2:12:15 am | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
Sun, May 29 2022 2:12:15 am | find: '/usr/lib/ssl/private': Permission denied
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | WARNING: The NVIDIA Driver was not detected. GPU functionality will not be available.
Sun, May 29 2022 2:12:15 am | Use Docker with NVIDIA Container Toolkit to start this container; see
Sun, May 29 2022 2:12:15 am | https://github.com/NVIDIA/nvidia-docker.
Sun, May 29 2022 2:12:15 am |  
Sun, May 29 2022 2:12:15 am | I0529 09:12:15.796242 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/pytorch/libtriton_pytorch.so
Sun, May 29 2022 2:12:16 am | WARNING: [Torch-TensorRT] - Unable to read CUDA capable devices. Return status: 35
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.033882 1 libtorch.cc:1227] TRITONBACKEND_Initialize: pytorch
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.033898 1 libtorch.cc:1237] Triton TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.033902 1 libtorch.cc:1243] 'pytorch' TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.033939 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so
Sun, May 29 2022 2:12:16 am | 2022-05-29 09:12:16.155397: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Sun, May 29 2022 2:12:16 am | 2022-05-29 09:12:16.179070: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.179123 1 tensorflow.cc:2176] TRITONBACKEND_Initialize: tensorflow
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.179140 1 tensorflow.cc:2186] Triton TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.179144 1 tensorflow.cc:2192] 'tensorflow' TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.179148 1 tensorflow.cc:2216] backend configuration:
Sun, May 29 2022 2:12:16 am | {}
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.179187 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/onnxruntime/libtriton_onnxruntime.so
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.180411 1 onnxruntime.cc:2232] TRITONBACKEND_Initialize: onnxruntime
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.180427 1 onnxruntime.cc:2242] Triton TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.180430 1 onnxruntime.cc:2248] 'onnxruntime' TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.180432 1 onnxruntime.cc:2278] backend configuration:
Sun, May 29 2022 2:12:16 am | {}
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.187086 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/openvino_2021_2/libtriton_openvino_2021_2.so
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.194832 1 openvino.cc:1234] TRITONBACKEND_Initialize: openvino
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.194847 1 openvino.cc:1244] Triton TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.194851 1 openvino.cc:1250] 'openvino' TRITONBACKEND API version: 1.7
Sun, May 29 2022 2:12:16 am | W0529 09:12:16.194911 1 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.194926 1 cuda_memory_manager.cc:115] CUDA memory pool disabled
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.195588 1 model_config_utils.cc:659] Server side auto-completed config: name: "onnx-model"
Sun, May 29 2022 2:12:16 am | platform: "onnxruntime_onnx"
Sun, May 29 2022 2:12:16 am | input {
Sun, May 29 2022 2:12:16 am | name: "images"
Sun, May 29 2022 2:12:16 am | data_type: TYPE_FP32
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | }
Sun, May 29 2022 2:12:16 am | output {
Sun, May 29 2022 2:12:16 am | name: "boxes"
Sun, May 29 2022 2:12:16 am | data_type: TYPE_FP32
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | dims: 4
Sun, May 29 2022 2:12:16 am | }
Sun, May 29 2022 2:12:16 am | output {
Sun, May 29 2022 2:12:16 am | name: "labels"
Sun, May 29 2022 2:12:16 am | data_type: TYPE_INT64
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | }
Sun, May 29 2022 2:12:16 am | output {
Sun, May 29 2022 2:12:16 am | name: "scores"
Sun, May 29 2022 2:12:16 am | data_type: TYPE_FP32
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | }
Sun, May 29 2022 2:12:16 am | output {
Sun, May 29 2022 2:12:16 am | name: "caption_locations"
Sun, May 29 2022 2:12:16 am | data_type: TYPE_INT64
Sun, May 29 2022 2:12:16 am | dims: -1
Sun, May 29 2022 2:12:16 am | }
Sun, May 29 2022 2:12:16 am | default_model_filename: "model.onnx"
Sun, May 29 2022 2:12:16 am | backend: "onnxruntime"
Sun, May 29 2022 2:12:16 am |  
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.195634 1 model_repository_manager.cc:700] AsyncLoad() 'onnx-model'
Sun, May 29 2022 2:12:16 am | W0529 09:12:16.195700 1 model_repository_manager.cc:203] ignore version directory 'docs' which fails to convert to integral number
Sun, May 29 2022 2:12:16 am | W0529 09:12:16.195718 1 model_repository_manager.cc:203] ignore version directory 'test_dataset' which fails to convert to integral number
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.195728 1 model_repository_manager.cc:939] TriggerNextAction() 'onnx-model' version 1: 1
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.195733 1 model_repository_manager.cc:975] Load() 'onnx-model' version 1
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.195735 1 model_repository_manager.cc:994] loading: onnx-model:1
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.295934 1 model_repository_manager.cc:1052] CreateModel() 'onnx-model' version 1
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296012 1 onnxruntime.cc:2313] TRITONBACKEND_ModelInitialize: onnx-model (version 1)
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296743 1 model_config_utils.cc:1608] ModelConfig 64-bit fields:
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296756 1 model_config_utils.cc:1610] ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296759 1 model_config_utils.cc:1610] ModelConfig::dynamic_batching::max_queue_delay_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296763 1 model_config_utils.cc:1610] ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296766 1 model_config_utils.cc:1610] ModelConfig::ensemble_scheduling::step::model_version
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296769 1 model_config_utils.cc:1610] ModelConfig::input::dims
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296772 1 model_config_utils.cc:1610] ModelConfig::input::reshape::shape
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296775 1 model_config_utils.cc:1610] ModelConfig::instance_group::secondary_devices::device_id
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296780 1 model_config_utils.cc:1610] ModelConfig::model_warmup::inputs::value::dims
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296783 1 model_config_utils.cc:1610] ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296787 1 model_config_utils.cc:1610] ModelConfig::optimization::cuda::graph_spec::input::value::dim
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296791 1 model_config_utils.cc:1610] ModelConfig::output::dims
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296794 1 model_config_utils.cc:1610] ModelConfig::output::reshape::shape
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296797 1 model_config_utils.cc:1610] ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296801 1 model_config_utils.cc:1610] ModelConfig::sequence_batching::max_sequence_idle_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296804 1 model_config_utils.cc:1610] ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296808 1 model_config_utils.cc:1610] ModelConfig::sequence_batching::state::dims
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296811 1 model_config_utils.cc:1610] ModelConfig::sequence_batching::state::initial_state::dims
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.296814 1 model_config_utils.cc:1610] ModelConfig::version_policy::specific::versions
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.297022 1 onnxruntime.cc:2356] TRITONBACKEND_ModelInstanceInitialize: onnx-model (CPU device 0)
Sun, May 29 2022 2:12:16 am | I0529 09:12:16.297035 1 backend_model_instance.cc:68] Creating instance onnx-model on CPU using artifact 'model.onnx'
Sun, May 29 2022 2:12:16 am | 2022-05-29 09:12:16.297089284 [I:onnxruntime:, inference_session.cc:273 operator()] Flush-to-zero and denormal-as-zero are off
Sun, May 29 2022 2:12:16 am | 2022-05-29 09:12:16.297103284 [I:onnxruntime:, inference_session.cc:280 ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true


```

Pod.Yaml

```
- image: cloudopscontainerregistrydevglobal.azurecr.io/tab-detection:505921
    imagePullPolicy: IfNotPresent
    name: tab-detection
    resources:
      limits:
        cpu: "5"
        memory: 5Gi
      requests:
        cpu: "5"
        memory: 5Gi
    securityContext:
      privileged: true
      runAsGroup: 18003
      runAsUser: 18002
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8768r
      readOnly: true
```

**Comment by Tabrizian** [comment]
@randomguy2022 @kthui has fixed a number of issues related to Python backend hangs [here ](https://github.com/triton-inference-server/python_backend/commit/32974481c4875ad22bf318dcb2b80e316cdf5065)and [here](https://github.com/triton-inference-server/python_backend/commit/00468e5f9d4d61c4b2fabf941b87424291e81e36). They will be included in 23.02 release. If they still didn't resolve the hang, please open a new issue.
