### ISSUE TITLE
Unable to load shared library: libc10.so when building Pytorch backend using Docker image

### ISSUE THREAD

**Issue by mhbassel** [triton-inference-server/server#5232]
Hello everyone!

I am trying to build custom Pytorch backend using Docker image and following the instructions [here](https://github.com/triton-inference-server/pytorch_backend/tree/r22.12).

Steps:

1.  Cloning the backend Repo
2.  Pulling the Pytorch image: nvcr.io/nvidia/pytorch:22.12-py3 and add my modifications 
3. Running the command:
```
cmake -DTRITON_BACKEND_REPO_TAG=r22.12 -DTRITON_CORE_REPO_TAG=r22.12 -DTRITON_COMMON_REPO_TAG=r22.12 -DCMAKE_INSTALL_PREFIX:PATH=`pwd`/install -DTRITON_PYTORCH_DOCKER_IMAGE="custom_pytorch:v1" ..
```
4. Running `make install`:
```
[  3%] Building NVCC (Device) object _deps/repo-backend-build/CMakeFiles/kernel-library-new.dir/src/kernel-library-new_generated_kernel.cu.o
[  7%] Linking CXX static library libkernel-library-new.a
[  7%] Built target kernel-library-new
[ 11%] Extracting pytorch and torchvision libraries and includes from pytorch_backend_t3k:v1
Error: No such container: pytorch_backend_ptlib
error ignored...
7afa1bd31faf7e3a84d6339d1ddaffc6ed9b8851cbf0248b4a13ccbe926593f3
copying libmkl_avx2.so.1
copying libmkl_avx512.so.1
copying libmkl_core.so.1
copying libmkl_def.so.1
copying libmkl_gnu_thread.so.1
copying libmkl_intel_lp64.so.1
copying libmkl_intel_thread.so.1
copying libmkl_rt.so.1
copying libmkl_sequential.so.1
copying libmkl_vml_def.so.1
pytorch_backend_ptlib
[ 11%] Built target ptlib_target
[ 14%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/async_work_queue.cc.o
[ 18%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/error.cc.o
[ 22%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-async-work-queue.dir/src/thread_pool.cc.o
[ 25%] Linking CXX static library libtritonasyncworkqueue.a
[ 25%] Built target triton-common-async-work-queue
[ 29%] Building CXX object _deps/repo-core-build/CMakeFiles/triton-core-serverstub.dir/src/tritonserver_stub.cc.o
[ 33%] Linking CXX shared library libtritonserver.so
[ 33%] Built target triton-core-serverstub
[ 37%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_common.cc.o
[ 40%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_input_collector.cc.o
[ 44%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_memory.cc.o
[ 48%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model_instance.cc.o
[ 51%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_model.cc.o
[ 55%] Building CXX object _deps/repo-backend-build/CMakeFiles/triton-backend-utils.dir/src/backend_output_responder.cc.o
[ 59%] Linking CXX static library libtritonbackendutils.a
[ 59%] Built target triton-backend-utils
[ 62%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch.cc.o
[ 66%] Building CXX object CMakeFiles/triton-pytorch-backend.dir/src/libtorch_utils.cc.o
[ 70%] Linking CXX shared library libtriton_pytorch.so
[ 70%] Built target triton-pytorch-backend
[ 74%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-error.dir/src/error.cc.o
[ 77%] Linking CXX static library libtritoncommonerror.a
[ 77%] Built target triton-common-error
[ 81%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-logging.dir/src/logging.cc.o
[ 85%] Linking CXX static library libtritoncommonlogging.a
[ 85%] Built target triton-common-logging
[ 88%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-thread-pool.dir/src/thread_pool.cc.o
[ 92%] Linking CXX static library libtritonthreadpool.a
[ 92%] Built target triton-common-thread-pool
[ 96%] Building CXX object _deps/repo-common-build/CMakeFiles/triton-common-table-printer.dir/src/table_printer.cc.o
[100%] Linking CXX static library libtritontableprinter.a
[100%] Built target triton-common-table-printer
Install the project...
-- Install configuration: "Release"
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritonasyncworkqueue.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritoncommonerror.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritoncommonlogging.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritontableprinter.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritonthreadpool.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/model_config.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/sync_queue.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/async_work_queue.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/error.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/thread_pool.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/table_printer.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/logging.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/triton_json.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/common/nvtx.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCommon/TritonCommonTargets.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCommon/TritonCommonTargets-release.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCommon/TritonCommonConfig.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/stubs/libtritonserver.so
-- Up-to-date: /media/ssdraid/training/triton/pytorch_backend/build/install/include
-- Up-to-date: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/core
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/core/tritonrepoagent.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/core/tritonserver.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/core/tritonbackend.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCore/TritonCoreTargets.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCore/TritonCoreTargets-release.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonCore/TritonCoreConfig.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libtritonbackendutils.a
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/libkernel-library-new.a
-- Up-to-date: /media/ssdraid/training/triton/pytorch_backend/build/install/include
-- Up-to-date: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_output_responder.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_input_collector.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_common.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_model_instance.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_memory.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/include/triton/backend/backend_model.h
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonBackend/TritonBackendTargets.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonBackend/TritonBackendTargets-release.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonBackend/TritonBackendConfig.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtriton_pytorch.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libc10.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libc10_cuda.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtorch.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtorch_cpu.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtorch_cuda.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtorch_global_deps.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libtorchvision.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_avx2.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_avx512.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_core.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_def.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_gnu_thread.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_intel_lp64.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_intel_thread.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_rt.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_sequential.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libmkl_vml_def.so.1
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_video.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_videoio.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_highgui.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_imgcodecs.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_imgproc.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_core.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_calib3d.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_flann.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libopencv_features2d.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libpng16.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/libjpeg.so
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/backends/pytorch/LICENSE.pytorch
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonPyTorchBackend/TritonPyTorchBackendTargets.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonPyTorchBackend/TritonPyTorchBackendTargets-release.cmake
-- Installing: /media/ssdraid/training/triton/pytorch_backend/build/install/lib/cmake/TritonPyTorchBackend/TritonPyTorchBackendConfig.cmake
```
5. Copying the library files to a Triton container and commit it
6. Run the new Triton container causes the following error:
```
W0110 17:49:49.075569 563 pinned_memory_manager.cc:236] Unable to allocate pinned system memory, pinned memory pool will not be available: CUDA driver version is insufficient for CUDA runtime version
I0110 17:49:49.075685 563 cuda_memory_manager.cc:115] CUDA memory pool disabled
I0110 17:49:49.079529 563 model_lifecycle.cc:459] loading: image_encoder:1
I0110 17:49:49.079592 563 model_lifecycle.cc:459] loading: text_encoder:1
E0110 17:49:49.081494 563 model_lifecycle.cc:597] failed to load 'image_encoder' version 1: Not found: unable to load shared library: libc10.so: cannot open shared object file: No such file or directory
E0110 17:49:49.082707 563 model_lifecycle.cc:597] failed to load 'text_encoder' version 1: Not found: unable to load shared library: libc10.so: cannot open shared object file: No such file or directory
I0110 17:49:49.082908 563 server.cc:563] 
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+

I0110 17:49:49.082950 563 server.cc:590] 
+---------+------+--------+
| Backend | Path | Config |
+---------+------+--------+
+---------+------+--------+

I0110 17:49:49.083005 563 server.cc:633] 
+---------------+---------+-----------------------------------------------------------------------------------------------------------------------------+
| Model         | Version | Status                                                                                                                      |
+---------------+---------+-----------------------------------------------------------------------------------------------------------------------------+
| image_encoder | 1       | UNAVAILABLE: Not found: unable to load shared library: libc10.so: cannot open shared object file: No such file or directory |
| text_encoder  | 1       | UNAVAILABLE: Not found: unable to load shared library: libc10.so: cannot open shared object file: No such file or directory |
+---------------+---------+-----------------------------------------------------------------------------------------------------------------------------+

I0110 17:49:49.083245 563 metrics.cc:757] Collecting CPU metrics
I0110 17:49:49.083423 563 tritonserver.cc:2264] 
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                               |
| server_version                   | 2.29.0                                                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | /models/                                                                                                                                                                                             |
| model_control_mode               | MODE_NONE                                                                                                                                                                                            |
| strict_model_config              | 0                                                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
| response_cache_byte_size         | 0                                                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                                                   |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

I0110 17:49:49.083477 563 server.cc:264] Waiting for in-flight requests to complete.
I0110 17:49:49.083488 563 server.cc:280] Timeout 30: Found 0 model versions that have in-flight inferences
I0110 17:49:49.083500 563 server.cc:295] All models are stopped, unloading models
I0110 17:49:49.083508 563 server.cc:302] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
```
Any idea why this is happening please?
Thanks

**Comment by nv-kmcgill53** [comment]
Hi @mhbassel, it is likely the shared libraries you built/installed in the triton container are not found by [`ld.so`](https://man7.org/linux/man-pages/man8/ld.so.8.html). Can you ensure that your shared libraries are discoverable by the linker?

Under the hood Triton is using [`dlopen`](https://github.com/triton-inference-server/core/blob/main/src/shared_library.cc#L139-L144) to attempt library loading.

**Comment by mhbassel** [comment]
Thank you a lot @nv-kmcgill53 for the reply!

Indeed, after testing around with `dlopen` I realized that all my libraries couldn't be opened. Only after running:
```
export LD_LIBRARY_PATH="/opt/tritonserver/backends/pytorch/"
```
The problem solved.

Thank you again (:
