### ISSUE TITLE
How can I get OpenVINO model configure example?

### ISSUE THREAD

**Issue by zhaozhiming37** [triton-inference-server/server#6035]
**Description**
My OV model is loaded failed.

**Triton Information**
nvcr.io/nvidia/tritonserver:22.10-py3

**To Reproduce**
My config
```
name: "scrfd_ov"
backend: "openvino"
default_model_filename: "scrfd_face.xml"
max_batch_size: 8
version_policy { 
  latest {
    num_versions: 1
  }
}
input [
  {
    name: "input.1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 640, 640 ]
  }
]

output [
  {
    name: "score_8"
    data_type: TYPE_FP32
    dims: [12800, 1]
  },
  {
    name: "score_16"
    data_type: TYPE_FP32
    dims: [3200, 1]
  },
  {
    name: "score_32"
    data_type: TYPE_FP32
    dims: [800, 1]
  },
  {
    name: "bbox_8"
    data_type: TYPE_FP32
    dims: [12800, 4]
  },
  {
    name: "bbox_16"
    data_type: TYPE_FP32
    dims: [3200, 4]
  },
  {
    name: "bbox_32"
    data_type: TYPE_FP32
    dims: [800, 4]
  },
  {
    name: "kps_8"
    data_type: TYPE_FP32
    dims: [12800, 10]
  },
  {
    name: "kps_16"
    data_type: TYPE_FP32
    dims: [3200, 10]
  },
  {
    name: "kps_32"
    data_type: TYPE_FP32
    dims: [800, 10]
  }
]
instance_group [
  { 
    count: 4
    kind: KIND_CPU
  }
]

dynamic_batching {
}

optimization {
  input_pinned_memory {
    enable: true
  }
  output_pinned_memory {
    enable: true
  }
}

model_warmup [
  {
    name: "zero_tensor"
    batch_size: 1
    inputs {
      key: "input.1"
      value: {
        data_type: TYPE_FP32
        dims: [3, 640, 640]
        zero_data: true
      }
    }
  },
  {
    name: "random_tensor"
    batch_size: 1
    inputs {
      key: "input.1"
      value: {
        data_type: TYPE_FP32
        dims: [3, 640, 640]
        random_data: true
      }
    }
  }
]

```

log info

```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.10 (build 47208631)
Triton Server Version 2.27.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

WARNING: CUDA Minor Version Compatibility mode ENABLED.
  Using driver version 515.76 which has support for CUDA 11.7.  This container
  was built with CUDA 11.8 and will be run in Minor Version Compatibility mode.
  CUDA Forward Compatibility is preferred over Minor Version Compatibility for use
  with this container but was unavailable:
  [[Forward compatibility was attempted on non supported HW (CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE) cuInit()=804]]
  See https://docs.nvidia.com/deploy/cuda-compatibility/ for details.

I0707 07:43:15.084486 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x7f1450000000' with size 268435456
I0707 07:43:15.084760 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I0707 07:43:15.086420 1 model_config_utils.cc:646] Server side auto-completed config: name: "scrfd_ov"
version_policy {
  latest {
    num_versions: 1
  }
}
max_batch_size: 8
input {
  name: "input.1"
  data_type: TYPE_FP32
  format: FORMAT_NCHW
  dims: 3
  dims: 640
  dims: 640
}
output {
  name: "score_8"
  data_type: TYPE_FP32
  dims: 12800
  dims: 1
}
output {
  name: "score_16"
  data_type: TYPE_FP32
  dims: 3200
  dims: 1
}
output {
  name: "score_32"
  data_type: TYPE_FP32
  dims: 800
  dims: 1
}
output {
  name: "bbox_8"
  data_type: TYPE_FP32
  dims: 12800
  dims: 4
}
output {
  name: "bbox_16"
  data_type: TYPE_FP32
  dims: 3200
  dims: 4
}
output {
  name: "bbox_32"
  data_type: TYPE_FP32
  dims: 800
  dims: 4
}
output {
  name: "kps_8"
  data_type: TYPE_FP32
  dims: 12800
  dims: 10
}
output {
  name: "kps_16"
  data_type: TYPE_FP32
  dims: 3200
  dims: 10
}
output {
  name: "kps_32"
  data_type: TYPE_FP32
  dims: 800
  dims: 10
}
instance_group {
  count: 4
  kind: KIND_CPU
}
default_model_filename: "scrfd_face.xml"
dynamic_batching {
}
optimization {
  input_pinned_memory {
    enable: true
  }
  output_pinned_memory {
    enable: true
  }
}
model_warmup {
  name: "zero_tensor"
  batch_size: 1
  inputs {
    key: "input.1"
    value {
      data_type: TYPE_FP32
      dims: 3
      dims: 640
      dims: 640
      zero_data: true
    }
  }
}
model_warmup {
  name: "random_tensor"
  batch_size: 1
  inputs {
    key: "input.1"
    value {
      data_type: TYPE_FP32
      dims: 3
      dims: 640
      dims: 640
      random_data: true
    }
  }
}
backend: "openvino"

I0707 07:43:15.086552 1 model_lifecycle.cc:459] loading: scrfd_ov:1
I0707 07:43:15.086661 1 backend_model.cc:302] Adding default backend config setting: default-max-batch-size,4
I0707 07:43:15.086687 1 shared_library.cc:108] OpenLibraryHandle: /opt/tritonserver/backends/openvino/libtriton_openvino.so
I0707 07:43:15.092909 1 openvino.cc:1343] TRITONBACKEND_Initialize: openvino
I0707 07:43:15.092920 1 openvino.cc:1353] Triton TRITONBACKEND API version: 1.10
I0707 07:43:15.092926 1 openvino.cc:1359] 'openvino' TRITONBACKEND API version: 1.10
I0707 07:43:15.092945 1 openvino.cc:1569] TRITONBACKEND_GetBackendAttribute: setting attributes
I0707 07:43:15.093215 1 openvino.cc:1436] TRITONBACKEND_ModelInitialize: scrfd_ov (version 1)
I0707 07:43:15.093605 1 model_config_utils.cc:1783] ModelConfig 64-bit fields:
I0707 07:43:15.093612 1 model_config_utils.cc:1785]     ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
I0707 07:43:15.093617 1 model_config_utils.cc:1785]     ModelConfig::dynamic_batching::max_queue_delay_microseconds
I0707 07:43:15.093621 1 model_config_utils.cc:1785]     ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
I0707 07:43:15.093625 1 model_config_utils.cc:1785]     ModelConfig::ensemble_scheduling::step::model_version
I0707 07:43:15.093628 1 model_config_utils.cc:1785]     ModelConfig::input::dims
I0707 07:43:15.093632 1 model_config_utils.cc:1785]     ModelConfig::input::reshape::shape
I0707 07:43:15.093636 1 model_config_utils.cc:1785]     ModelConfig::instance_group::secondary_devices::device_id
I0707 07:43:15.093640 1 model_config_utils.cc:1785]     ModelConfig::model_warmup::inputs::value::dims
I0707 07:43:15.093645 1 model_config_utils.cc:1785]     ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
I0707 07:43:15.093649 1 model_config_utils.cc:1785]     ModelConfig::optimization::cuda::graph_spec::input::value::dim
I0707 07:43:15.093653 1 model_config_utils.cc:1785]     ModelConfig::output::dims
I0707 07:43:15.093657 1 model_config_utils.cc:1785]     ModelConfig::output::reshape::shape
I0707 07:43:15.093661 1 model_config_utils.cc:1785]     ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
I0707 07:43:15.093665 1 model_config_utils.cc:1785]     ModelConfig::sequence_batching::max_sequence_idle_microseconds
I0707 07:43:15.093669 1 model_config_utils.cc:1785]     ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
I0707 07:43:15.093673 1 model_config_utils.cc:1785]     ModelConfig::sequence_batching::state::dims
I0707 07:43:15.093678 1 model_config_utils.cc:1785]     ModelConfig::sequence_batching::state::initial_state::dims
I0707 07:43:15.093681 1 model_config_utils.cc:1785]     ModelConfig::version_policy::specific::versions
terminate called after throwing an instance of 'triton::backend::BackendModelInstanceException'

```

my model and config
[scrfd_ov.zip](https://github.com/triton-inference-server/server/files/11979502/scrfd_ov.zip)

**Expected behavior**

**Comment by SerSmith** [comment]
I am having the same problem with nvcr.io/nvidia/tritonserver:23.05-py3

**Comment by tanmayv25** [comment]
@kthui ^^^

**Comment by SerSmith** [comment]
In my case the problem was in dynamic_axes. I've recreated onnx model with fixed size and autocreated config.pbtxt. That has solved my issue. The result config is 
[config.pbtxt.zip](https://github.com/triton-inference-server/server/files/12146676/config.pbtxt.zip)

**Comment by dyastremsky** [comment]
Thanks for sharing your solution!
