### ISSUE TITLE
model loading failed if uses warmup

### ISSUE THREAD

**Issue by AlexanderKomarov** [triton-inference-server/server#6670]
**Description**
TritonServer fails on loading models when I test warmuping for 4 equal ONNX models.

I use [mobilenetv2 from ONNX Model Zoo](https://github.com/onnx/models/blob/main/vision/classification/mobilenet/model/mobilenetv2-12.onnx). But actually I tested on a couple of various models.
My model_repo is just 4 equal models with warmup sections. I got the following error:

`E1207 13:32:37.340045 362 model_lifecycle.cc:621] failed to load 'model' version 1: Internal: onnx runtime error 1: /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:121 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] /workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_call.cc:114 std::conditional_t<THRW, void, onnxruntime::common::Status> onnxruntime::CudaCall(ERRTYPE, const char*, const char*, ERRTYPE, const char*, const char*, int) [with ERRTYPE = cudaError; bool THRW = true; std::conditional_t<THRW, void, onnxruntime::common::Status> = void] CUDA failure 900: operation not permitted when stream is capturing ; GPU=0 ; hostname=14b3d2c3b72b ; file=/workspace/onnxruntime/onnxruntime/core/providers/cuda/cuda_execution_provider.cc ; line=239 ; expr=cudaDeviceSynchronize(); 
`
If I remove warmup section the error is gone.
if I pass `--model-load-thread-count 1` to TritonServer the error is gone.

**Triton Information**
nvcr.io/nvidia/tritonserver:23.11-py3 
GPU: T4
Driver Version: 535.54.03    CUDA Version: 12.2 

**To Reproduce**
Steps to reproduce the behavior.

Create model_repo with 4 equal models and equal config.pbtxt.

config.pbtxt
```
model_warmup [
  {
    name : "batch 1"
    batch_size: 1
    inputs {
      key: "input"
      value: {
        data_type: TYPE_FP32
        dims: [ 3, 224, 224 ]
        random_data: true
      }
    }
    count: 1
  }
]
```

**Expected behavior**
Models successfully load.

**Comment by AlexanderKomarov** [comment]
Sure, thank you for the quick response.

I uploaded my model_repo.
https://www.dropbox.com/scl/fi/c9yu99rokvutq3px862po/triton_model_repo.zip?rlkey=4uqd2adetrr54u1dl6zyfz8fp&dl=0

I test on AWS. The instance is based on [this AMI](https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#ImageDetails:imageId=ami-0d09ad178e7e780d1). I use `g4dn.xlarge`.

I use the following commands:
```
docker run --gpus all --rm -it -v $(pwd):/tmp_/ nvcr.io/nvidia/tritonserver:23.11-py3
./bin/tritonserver --model-repository /tmp_/model_repo_in/
````

**Comment by AlexanderKomarov** [comment]
Hello @fpetrini15 did you manage to reproduce the issue?
If you need anything from my side please feel free to write me.

**Comment by fpetrini15** [comment]
Hello @AlexanderKomarov, apologies for the late response! I was able to reproduce the issue using the repo you provided. I'll create a ticket for our team to investigate further.

**Comment by lminer** [comment]
I'm seeing this issue too.

**Comment by lminer** [comment]
Could this be an onnxruntime issue? https://github.com/microsoft/onnxruntime/issues/15002

**Comment by lminer** [comment]
I'm seeing this issue even without warmup and it happens intermittently.

**Comment by luvwinnie** [comment]
is this fixed? i got same errors.

**Comment by mhbassel** [comment]
> this issue is for cuda graph error in single thread. Your reported error is another issue of multi-threading.

Stream capturing error shall not appear when cuda graph is not enabled. If you see that error in onnx test runner, that basically means ORT has some code is not thread-safe, which cause buffer overrun and mess up the call stack.

@fpetrini15 This is probably happens when building the onnxruntime backend with CUDA Graphs enabled, but nevertheless Triton should be able to overcome this somehow or at least having the backend without CUDA Graphs enabled.

**Comment by AlexanderKomarov** [comment]
It seems like I found a workaround. The cause comes from `EXHAUSTIVE`  opt level of cudnn.

So if set `parameters { key: "cudnn_conv_algo_search" value: { string_value: "2" } }` in config.pbtxt, everything works.

**Comment by tham-tran-ts** [comment]
is this fixed? i got same errors.

**Comment by AlexanderKomarov** [comment]
not yet, but I have found two workarounds: use tensorRT, use base level of cudnn optimization.

I tested on the latest triton:24.11

**Comment by ghost** [comment]
> not yet, but I have found two workarounds: use tensorRT, use base level of cudnn optimization.
> 
> I tested on the latest triton:24.11

`--model-load-thread-count 1` is also a workaround I think
