### ISSUE TITLE
Create multiple instance with KIND_MODEL on multiple GPU

### ISSUE THREAD

**Issue by warlock135** [triton-inference-server/server#6855]
**Description**
I tried to create 4 separated instances of vllm on 4 different GPUs. And I couldn't figure out how to properly configure triton to do so when using KIND_MODEL as model instance group kind.
With CUDA_VISIBLE_DEVICES set to (0-3)
Using below configs:
```
instance_group [
  {
    count: 1
    kind: KIND_MODEL
 }
]
```
or
```
instance_group [
  {
    kind: KIND_MODEL
  }
]
```
4 tritonserver process start on 4 GPUs, but only 1 model instance is initialized on GPU 0

Using below config:
```
instance_group [
  {
    count: 4
    kind: KIND_MODEL
  }
]
```
or
```
instance_group [
  {
    kind: KIND_MODEL
  }
]
instance_group [
  {
    kind: KIND_MODEL
  }
]
instance_group [
  {
    kind: KIND_MODEL
  }
]
instance_group [
  {
    kind: KIND_MODEL
  }
]
```
or
```
instance_group [
  {
    kind: KIND_MODEL
  },
  {
    kind: KIND_MODEL
  },
  {
    kind: KIND_MODEL
  },
  {
    kind: KIND_MODEL
  }
]
```
4 tritonserver process start on 4 GPU, and 4 model instance start on GPU 0 (and lead to OOM)

The only way to start 4 instances on 4 GPUs as in the docs ([By default, a single execution instance of the model is created for each GPU available in the system](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html)) is switching into KIND_GPU.

**Triton Information**
What version of Triton are you using?

> nvcr.io/nvidia/tritonserver:24.01-vllm-python-py3

Are you using the Triton container or did you build it yourself?

> Triton container from NGC

**To Reproduce**
Run tritonserver inside container with multiple GPUs and default configs 

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
4 instances of vllm should be created on 4 GPUs

**Comment by rmccorm4** [comment]
Hi @warlock135,

Thanks for bringing this up. Since the vllm_backend is implemented as a python model - it has complete control over what devices it uses, and it looks like [our implementation is not explicitly telling vLLM which GPU to use](https://github.com/triton-inference-server/vllm_backend/blob/52c1c3ce7500581469150e38f61b3a200ac3e82a/src/model.py#L115-L118), so it is likely defaulting to GPU 0 on each instance. 

In order to achieve what you are trying, you may be able to modify the vllm model.py implementation to set `CUDA_VISIBLE_DEVICES` manually in each instance. 

To map model instance -> CUDA_VISIBLE_DEVICE setting, you can try using `KIND_GPU` (for the default 1 instance per GPU) and checking the following value in python model's initialize function. Something like this may work:
```python
# /opt/tritonserver/backends/vllm/model.py

class TritonPythonModel:
  def initialize(self, args):
    ...
    # Try to explicitly isolate GPUs before initializing VLLM engine
    device_id = args["model_instance_device_id"] # 0 / 1 / 2 / 3 
    os.environ["CUDA_VISIBLE_DEVICES"] = device_id
    
...
```

I don't know off the top of my head if this will work, but it seems like a good first thing to try to unblock you. 

In the meantime, CC @oandreeva-nv @pskiran1 @Tabrizian if you have thoughts on improving GPU isolation/handling for vLLM backend.

**Comment by warlock135** [comment]
> To map model instance -> `CUDA_VISIBLE_DEVICES` setting, you can try using `KIND_GPU` (for the default 1 instance per GPU) and checking the following value in python model's initialize function. Something like this may work:

Thank for your reply. 
Using KIND_GPU and set CUDA_VISIBLE_DEVICES before initializing vllm engine make it works as expected.
I will try starting 4 instances with KIND_MODEL and parsing the model_instance_name.

**Comment by Tabrizian** [comment]
Perhaps we could add another parameter for vLLM to indicate the GPUs that are available to the model and vLLM backend would consume those parameters to decide which GPUs it should place the model on.

**Comment by rmccorm4** [comment]
Medium term I also think we should consider enhancing KIND_GPU to support the notion of multiple GPUs for a single model, to give Triton/core a better idea for resource management and control

**Comment by dyastremsky** [comment]
Closing due to inactivity. Please re-open the issue if you would like to follow up with this issue.

@Tabrizian @rmccorm4 If we think those two features may add values, perhaps we can file enhancement tickets. We can link to this GitHub issue.

**Comment by mse700** [comment]
Hi
What if one wants to deploy one model on two gpus. I am trying to deploy the llama2-70b using vllm backend on 2 H100 GPUs. I have used the exact model.json and config.pbtxt file as this repository. but the following error appears:

utOfMemoryError: CUDA out of memory. Tried to allocate 896.00 MiB. GPU 0 has a total capacty of 93.02 GiB of which 17.81 MiB is free. Process 3521343 has 582.00 MiB memory in use. Process 3521538 has 55.76 GiB memory in use. Process 3521537 has 36.64 GiB memory in use. Of the allocated memory 54.96 GiB is allocated by PyTorch, and 448.00 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by oandreeva-nv** [comment]
Hi @mse700 , may I ask you to share full log?

**Comment by hillarysanders** [comment]
@mse700 I think llama2-70b won't fit on 2 H100 GPUs.

**Comment by mse700** [comment]
@hillarysanders @oandreeva-nv 
Sorry for the late Response. Actually, I have forgotten to set the `tensor_parallelism` option in model.json dile to true. When it is set, then the server runs as expected.

**Comment by oandreeva-nv** [comment]
Thanks for the response, @mse700 . Happy to hear that everything is working for you.

**Comment by GermanGebel** [comment]
Hi!

> ```python
> # /opt/tritonserver/backends/vllm/model.py
> 
> class TritonPythonModel:
>   def initialize(self, args):
>     ...
>     # Try to explicitly isolate GPUs before initializing VLLM engine
>     device_id = args["model_instance_device_id"] # 0 / 1 / 2 / 3 
>     os.environ["CUDA_VISIBLE_DEVICES"] = device_id
> ...
> ```

and also commenting `torch.cuda.set_device` works for me.

```python
class TritonPythonModel:
    def validate_device_config(self):
        ...
        if triton_kind == "GPU" and triton_device_id >= 0:
            self.logger.log_info(
                f"Detected KIND_GPU model instance, explicitly setting GPU device={triton_device_id} for {triton_instance}"
            )
            # torch.cuda.set_device(triton_device_id)  <------------- comment or drop this
```


Else I gave errors:
```
I1022 13:13:52.359091 1 pb_stub.cc:366] "Failed to initialize Python stub: RuntimeError: CUDA error: invalid device ordinal\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n\nAt:\n  /tmp/python_env_GTkQXk/9/lib/python3.10/site-packages/torch/cuda/__init__.py(420): set_device\n  /tmp/folder2rUlhY/1/model.py(238): validate_device_config\n  /tmp/folder2rUlhY/1/model.py(167): init_engine\n  /tmp/folder2rUlhY/1/model.py(120): initialize\n"
E1022 13:13:53.178914 1 backend_model.cc:692] "ERROR: Failed to create instance: RuntimeError: CUDA error: invalid device ordinal\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n\nAt:\n  /tmp/python_env_GTkQXk/9/lib/python3.10/site-packages/torch/cuda/__init__.py(420): set_device\n  /tmp/folder2rUlhY/1/model.py(238): validate_device_config\n  /tmp/folder2rUlhY/1/model.py(167): init_engine\n  /tmp/folder2rUlhY/1/model.py(120): initialize\n"
E1022 13:13:53.444357 1 model_lifecycle.cc:641] "failed to load 'vllm_test' version 1: Internal: RuntimeError: CUDA error: invalid device ordinal\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n\n\nAt:\n  /tmp/python_env_GTkQXk/9/lib/python3.10/site-packages/torch/cuda/__init__.py(420): set_device\n  /tmp/folder2rUlhY/1/model.py(238): validate_device_config\n  /tmp/folder2rUlhY/1/model.py(167): init_engine\n  /tmp/folder2rUlhY/1/model.py(120): initialize\n"
```

**Comment by oandreeva-nv** [comment]
Hi @GermanGebel ,

Were you launching one model on multiple GPUs ? or you were trying to put a model onto a single gpu with rank > 0 ?
