### ISSUE TITLE
vLLM backend fails to properly initialize tensor parallelism across multiple GPUs

### ISSUE THREAD

**Issue by omerap12** [triton-inference-server/server#8235]
When using the vLLM backend with tensor parallelism enabled, the model initialization fails with an OOM error on GPU 0, despite having multiple GPUs available and configured for tensor parallelism.

### Environment
- Triton Server Version: 2.58.0
- Hardware: AWS g6e.12xlarge (4x NVIDIA L40S GPUs, 48GB each)
- Model: meta-llama/Llama-4-Scout-17B-16E

### Configuration
Triton Config:
```bash
backend: "vllm"
instance_group [
  {
    count: 1
    kind: KIND_MODEL
  }
]
```

### vLLM Config:
```bash
{
    "model": "meta-llama/Llama-4-Scout-17B-16E",
    "disable_log_requests": "true",
    "gpu_memory_utilization": 0.9,
    "enforce_eager": "true",
    "tensor_parallel_size": 4,
    "swap_space": 4,
    "disable_custom_all_reduce": true,
    "max_model_len": 4096
}
```

### Error log:
```bash
INFO 06-05 08:00:42 [llm_engine.py:243] Initializing a V0 LLM engine (v0.8.4+dc1a3e10.nv25.05) with config: model='meta-llama/Llama-4-Scout-17B-16E', speculative_config=None, tokenizer='meta-llama/Llama-4-Scout-17B-16E', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=true, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='auto', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=meta-llama/Llama-4-Scout-17B-16E, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=True, 
ERROR 06-05 08:00:46 [engine.py:448] CUDA out of memory. Tried to allocate 640.00 MiB. GPU 0 has a total capacity of 44.31 GiB of which 81.00 MiB is free. Process 1 has 0 bytes memory in use. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 43.05 GiB is allocated by PyTorch, and 111.16 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 06-05 08:00:46 [engine.py:448] Traceback (most recent call last):
ERROR 06-05 08:00:46 [engine.py:448]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
ERROR 06-05 08:00:46 [engine.py:448]     engine = MQLLMEngine.from_vllm_config(
ERROR 06-05 08:00:46 [engine.py:448]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-05 08:00:46 [engine.py:448]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
ERROR 06-05 08:00:46 [engine.py:448]     return cls(
ERROR 06-05 08:00:46 [engine.py:448]            ^^^^
ERROR 06-05 08:00:46 [engine.py:448]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
ERROR 06-05 08:00:46 [engine.py:448]     self.engine = LLMEngine(*args, **kwargs)
ERROR 06-05 08:00:46 [engine.py:448]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-05 08:00:46 [engine.py:448]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 282, in __init__
ERROR 06-05 08:00:46 [engine.py:448]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 06-05 08:00:46 [engine.py:448]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The server fails to start with an OOM error on GPU 0, despite tensor_parallel_size: 4 being set:
```bash
CUDA out of memory. Tried to allocate 640.00 MiB. GPU 0 has a total capacity of 44.31 GiB of which 81.00 MiB is free. Process 1 has 0 bytes memory in use. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 43.05 GiB is allocated by PyTorch, and 111.16 MiB is reserved by PyTorch but unallocated.
```

My question is as follows:
Why is the initial model loading happening only on GPU 0, rather than being properly distributed across all GPUs from the beginning? This seems to defeat the purpose of the tensor parallelism configuration. Is there something wrong with my setup, or am I misunderstanding how this is supposed to work?

**Comment by OswaldAKs** [comment]
This happens because PyTorch reserves some GPU memory (111 MiB here) but doesn’t allocate it yet, causing memory fragmentation. So even though some memory seems free, it’s not usable for large allocations like loading the model all at once.

vLLM loads most of the model on GPU 0 first before splitting, causes this temporary oom error.

I faced the same kind of issue when deploying the `llama-3.2-11b-vision-instruct` model. I fixed it by setting this:

```bash
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
```

This setting helps PyTorch manage memory to avoid fragmentation .

Hope this helps!

**Comment by omerap12** [comment]
> This happens because PyTorch reserves some GPU memory (111 MiB here) but doesn’t allocate it yet, causing memory fragmentation. So even though some memory seems free, it’s not usable for large allocations like loading the model all at once.
> 
> vLLM loads most of the model on GPU 0 first before splitting, causes this temporary oom error.
> 
> I faced the same kind of issue when deploying the `llama-3.2-11b-vision-instruct` model. I fixed it by setting this:
> 
> export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
> This setting helps PyTorch manage memory to avoid fragmentation .
> 
> Hope this helps!

Thanks for the response! I tried and got this again:
```bash
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 640.00 MiB. GPU 0 has a total capacity of 44.31 GiB of which 195.00 MiB is free. Process 1 has 0 bytes memory in use. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 43.03 GiB is allocated by PyTorch, and 19.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```


> vLLM loads most of the model on GPU 0 first before splitting, causes this temporary oom error.

This might be the issue but the all purpose of tensor parallelism is that you can use it to deploy a model that is too large to fit in a single GPU, but can fit in a single node with multiple GPUs.
So I'm not sure what I'm missing there.

**Comment by OswaldAKs** [comment]
If expandable_segments isn’t helping, try setting **CUDA_VISIBLE_DEVICES=1,2,3,0** to avoid GPU 0 being used first, also consider pre-downloading the model and loading it from a local path to reduce memory usage.

**Comment by omerap12** [comment]
> If expandable_segments isn’t helping, try setting **CUDA_VISIBLE_DEVICES=1,2,3,0** to avoid GPU 0 being used first, also consider pre-downloading the model and loading it from a local path to reduce memory usage.

Thanks! 
In my case, I had already pre-downloaded the model, but the main issue was that the model was simply too large for the 4 GPUs available. The solution was either to switch to a smaller model or use an instance with more GPUs - upgrading to more GPUs resolved it.

Closing the issue since it’s now resolved.
